Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2018-11, with the labels that each got.

#80 Base clock scoreboard fixing
  base/clock/gm4/functions/init.mcfunction
  base/clock/gm4/functions/tick.mcfunction
  base/clock/gm4/functions/update.mcfunction
Labels: update

#16 Add particles pack module
  gm4_particles_pack/data/better_armour_stands/tags/functions/apply_book.json
  gm4_particles_pack/data/gm4/functions/init.mcfunction
  gm4_particles_pack/data/gm4/functions/tick.mcfunction
  gm4_particles_pack/data/gm4/functions/update.mcfunction
  gm4_particles_pack/data/gm4/tags/functions/init_check.json
  gm4_particles_pack/data/gm4/tags/functions/pulse_check.json
  gm4_particles_pack/data/minecraft/tags/functions/load.json
  gm4_particles_pack/data/minecraft/tags/functions/tick.json
  gm4_particles_pack/data/particles_pack/functions/apply_book.mcfunction
  gm4_particles_pack/data/particles_pack/functions/init.mcfunction
  gm4_particles_pack/data/particles_pack/functions/init_check.mcfunction
  gm4_particles_pack/data/particles_pack/functions/main.mcfunction
  gm4_particles_pack/data/particles_pack/functions/particle.mcfunction
  gm4_particles_pack/data/particles_pack/functions/pulse_check.mcfunction
  gm4_particles_pack/pack.mcmeta
Labels: module, needs testing

#54 Ender Hoppers: Multiple Hopper Bug Fix
  gm4_ender_hoppers/data/ender_hoppers/functions/main.mcfunction
Labels: fix

#17 Add lightning rods module
  gm4_lightning_rods/data/custom_crafters/tags/functions/recipe_check.json
  gm4_lightning_rods/data/gm4/advancements/lightning_rods_shulker.json
  gm4_lightning_rods/data/gm4/advancements/root.json
  gm4_lightning_rods/data/gm4/tags/functions/init_check.json
  gm4_lightning_rods/data/gm4/tags/functions/pulse_check.json
  gm4_lightning_rods/data/lightning_rods/functions/boom.mcfunction
  gm4_lightning_rods/data/lightning_rods/functions/create_shulker.mcfunction
  gm4_lightning_rods/data/lightning_rods/functions/init.mcfunction
  gm4_lightning_rods/data/lightning_rods/functions/init_check.mcfunction
  gm4_lightning_rods/data/lightning_rods/functions/main.mcfunction
  gm4_lightning_rods/data/lightning_rods/functions/pulse_check.mcfunction
  gm4_lightning_rods/data/lightning_rods/functions/recipe_check.mcfunction
  gm4_lightning_rods/data/lightning_rods/functions/thrown.mcfunction
  gm4_lightning_rods/data/lightning_rods/loot_tables/shulker.json
  gm4_lightning_rods/pack.mcmeta
Labels: module, tested
