Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2018-09, with the labels that each got.

#15 Add counter to trapped signs when ray tracing to make sure the recursion ends
  gm4_trapped_signs/data/trapped_signs/functions/init.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/place_trapped_sign.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/ray.mcfunction
Labels: enhancement

#8 Add speed paths module
  gm4_speed_paths/data/gm4/advancements/root.json
  gm4_speed_paths/data/gm4/advancements/speed_paths.json
  gm4_speed_paths/data/gm4/functions/init.mcfunction
  gm4_speed_paths/data/gm4/functions/tick.mcfunction
  gm4_speed_paths/data/gm4/functions/update.mcfunction
  gm4_speed_paths/data/gm4/tags/functions/init_check.json
  gm4_speed_paths/data/gm4/tags/functions/pulse_check.json
  gm4_speed_paths/data/minecraft/tags/functions/load.json
  gm4_speed_paths/data/minecraft/tags/functions/tick.json
  gm4_speed_paths/data/speed_paths/functions/init.mcfunction
  gm4_speed_paths/data/speed_paths/functions/init_check.mcfunction
  gm4_speed_paths/data/speed_paths/functions/main.mcfunction
  gm4_speed_paths/data/speed_paths/functions/pulse_check.mcfunction
  gm4_speed_paths/pack.mcmeta
Labels: module

#3 Add better armor stands module
  gm4_better_armor_stands/data/better_armor_stands/functions/apply_book.mcfunction
  gm4_better_armor_stands/data/better_armor_stands/functions/init.mcfunction
  gm4_better_armor_stands/data/better_armor_stands/functions/init_check.mcfunction
  gm4_better_armor_stands/data/better_armor_stands/functions/main.mcfunction
  gm4_better_armor_stands/data/better_armor_stands/functions/pulse_check.mcfunction
  gm4_better_armor_stands/data/better_armor_stands/tags/functions/apply_book.json
  gm4_better_armor_stands/data/gm4/advancements/better_armor_stands.json
  gm4_better_armor_stands/data/gm4/advancements/root.json
  gm4_better_armor_stands/data/gm4/functions/init.mcfunction
  gm4_better_armor_stands/data/gm4/functions/tick.mcfunction
  gm4_better_armor_stands/data/gm4/functions/update.mcfunction
  gm4_better_armor_stands/data/gm4/tags/functions/init_check.json
  gm4_better_armor_stands/data/gm4/tags/functions/pulse_check.json
  gm4_better_armor_stands/data/minecraft/tags/functions/load.json
  gm4_better_armor_stands/data/minecraft/tags/functions/tick.json
  gm4_better_armor_stands/pack.mcmeta
Labels: module

#12 Add boots of ostara module
  gm4_boots_of_ostara/data/boots_of_ostara/functions/active.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/block_desire_lines.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/init.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/init_check.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/main.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/plant.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/plant/beetroot.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/plant/carrot.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/plant/potato.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/plant/wheat.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/pulse_check.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/recipe_check.mcfunction
  gm4_boots_of_ostara/data/custom_crafters/tags/functions/recipe_check.json
  gm4_boots_of_ostara/data/desire_lines/tags/functions/expansion.json
  gm4_boots_of_ostara/data/gm4/advancements/boots_of_ostara.json
  gm4_boots_of_ostara/data/gm4/advancements/root.json
  gm4_boots_of_ostara/data/gm4/functions/init.mcfunction
  gm4_boots_of_ostara/data/gm4/functions/tick.mcfunction
  gm4_boots_of_ostara/data/gm4/functions/update.mcfunction
  gm4_boots_of_ostara/data/gm4/tags/functions/init_check.json
  gm4_boots_of_ostara/data/gm4/tags/functions/pulse_check.json
  gm4_boots_of_ostara/data/minecraft/tags/functions/load.json
  gm4_boots_of_ostara/data/minecraft/tags/functions/tick.json
  gm4_boots_of_ostara/pack.mcmeta
Labels: module, tested

#11 Add desire lines module
  gm4_desire_lines/data/desire_lines/functions/init.mcfunction
  gm4_desire_lines/data/desire_lines/functions/init_check.mcfunction
  gm4_desire_lines/data/desire_lines/functions/main.mcfunction
  gm4_desire_lines/data/desire_lines/functions/path.mcfunction
  gm4_desire_lines/data/desire_lines/functions/player.mcfunction
  gm4_desire_lines/data/desire_lines/functions/pulse_check.mcfunction
  gm4_desire_lines/data/desire_lines/tags/blocks/breakable.json
  gm4_desire_lines/data/gm4/functions/init.mcfunction
  gm4_desire_lines/data/gm4/functions/tick.mcfunction
  gm4_desire_lines/data/gm4/functions/update.mcfunction
  gm4_desire_lines/data/gm4/tags/functions/init_check.json
  gm4_desire_lines/data/gm4/tags/functions/pulse_check.json
  gm4_desire_lines/data/minecraft/tags/functions/load.json
  gm4_desire_lines/data/minecraft/tags/functions/tick.json
  gm4_desire_lines/pack.mcmeta
Labels: module, tested

#1 Updated vertical rails
  gm4_vertical_rails/data/gm4/advancements/root.json
  gm4_vertical_rails/data/gm4/advancements/vertical_rails.json
  gm4_vertical_rails/data/gm4/functions/init.mcfunction
  gm4_vertical_rails/data/gm4/functions/tick.mcfunction
  gm4_vertical_rails/data/gm4/functions/update.mcfunction
  gm4_vertical_rails/data/gm4/tags/functions/init_check.json
  gm4_vertical_rails/data/gm4/tags/functions/pulse_check.json
  gm4_vertical_rails/data/minecraft/tags/functions/load.json
  gm4_vertical_rails/data/minecraft/tags/functions/tick.json
  gm4_vertical_rails/data/vertical_rails/functions/init.mcfunction
  gm4_vertical_rails/data/vertical_rails/functions/init_check.mcfunction
  gm4_vertical_rails/data/vertical_rails/functions/main.mcfunction
  gm4_vertical_rails/data/vertical_rails/functions/momentum.mcfunction
  gm4_vertical_rails/data/vertical_rails/functions/pulse_check.mcfunction
  gm4_vertical_rails/pack.mcmeta
Labels: module
