Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2018-12, with the labels that each got.

#9 Add enchantment extractors module
  gm4_enchantment_extractors/data/enchantment_extractors/functions/create.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/destroy.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/enchantment.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/extract.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/extract_failed.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/init.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/init_check.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/main.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/next_random.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/process.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/pulse_check.mcfunction
  gm4_enchantment_extractors/data/gm4/advancements/enchantment_extractors.json
  gm4_enchantment_extractors/data/gm4/advancements/enchantment_extractors_mending.json
  gm4_enchantment_extractors/data/gm4/advancements/root.json
  gm4_enchantment_extractors/data/gm4/tags/functions/init_check.json
  gm4_enchantment_extractors/data/gm4/tags/functions/pulse_check.json
  gm4_enchantment_extractors/pack.mcmeta
Labels: module, tested

#13 Add block compressor module
  gm4_block_compressors/data/block_compressors/functions/compress/16.mcfunction
  gm4_block_compressors/data/block_compressors/functions/compress/64.mcfunction
  gm4_block_compressors/data/block_compressors/functions/create.mcfunction
  gm4_block_compressors/data/block_compressors/functions/decompress/16.mcfunction
  gm4_block_compressors/data/block_compressors/functions/decompress/64.mcfunction
  gm4_block_compressors/data/block_compressors/functions/destroy.mcfunction
  gm4_block_compressors/data/block_compressors/functions/init.mcfunction
  gm4_block_compressors/data/block_compressors/functions/init_check.mcfunction
  gm4_block_compressors/data/block_compressors/functions/item.mcfunction
  gm4_block_compressors/data/block_compressors/functions/main.mcfunction
  gm4_block_compressors/data/block_compressors/functions/process.mcfunction
  gm4_block_compressors/data/block_compressors/functions/pulse_check.mcfunction
  gm4_block_compressors/data/block_compressors/functions/recipe_check.mcfunction
  gm4_block_compressors/data/custom_crafters/tags/functions/recipe_check.json
  gm4_block_compressors/data/gm4/advancements/block_compressors.json
  gm4_block_compressors/data/gm4/advancements/root.json
  gm4_block_compressors/data/gm4/tags/functions/init_check.json
  gm4_block_compressors/data/gm4/tags/functions/pulse_check.json
  gm4_block_compressors/pack.mcmeta
Labels: module, needs testing

#119 Fix #100 - Heart canister bug
  gm4_heart_canisters/data/heart_canisters/functions/apply_health_boost.mcfunction
  gm4_heart_canisters/data/heart_canisters/functions/check_heart_canisters.mcfunction
  gm4_heart_canisters/data/heart_canisters/functions/main.mcfunction
  gm4_heart_canisters/data/heart_canisters/functions/player.mcfunction
Labels: fix

#130 Add XP Storage
  gm4_xp_storage/data/gm4/tags/functions/init_check.json
  gm4_xp_storage/data/gm4/tags/functions/pulse_check.json
  gm4_xp_storage/data/xp_storage/functions/deposit_mode_check.mcfunction
  gm4_xp_storage/data/xp_storage/functions/dump_all.mcfunction
  gm4_xp_storage/data/xp_storage/functions/dump_level.mcfunction
  gm4_xp_storage/data/xp_storage/functions/init.mcfunction
  gm4_xp_storage/data/xp_storage/functions/init_check.mcfunction
  gm4_xp_storage/data/xp_storage/functions/main.mcfunction
  gm4_xp_storage/data/xp_storage/functions/point_report.mcfunction
  gm4_xp_storage/data/xp_storage/functions/point_report_ray.mcfunction
  gm4_xp_storage/data/xp_storage/functions/pulse_check.mcfunction
  gm4_xp_storage/data/xp_storage/functions/withdraw.mcfunction
  gm4_xp_storage/data/xp_storage/functions/xp_deposit_loop.mcfunction
  gm4_xp_storage/pack.mcmeta
Labels: module

#131 Zauber Cauldrons Vexmas Update
  gm4_zauber_cauldrons/data/gm4/advancements/zauber_cauldrons_wormhole.json
  gm4_zauber_cauldrons/data/zauber_cauldrons/advancements/consume_wormhole_bottle.json
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/extra_items/catch_possessed_items.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/extra_items/create_possessed_items.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/extra_items/failed_catch_possessed_items.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/extra_items/prepare_bottle.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/extra_items/release_from_bottle.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/recipe_checks.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/use_extra_items.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/arrival_animation.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/choose_dimension.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/teleport_to_dimension.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/init.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/init_check.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/main.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/blurry_wormhole.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/count_chorus.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/initiate_chorus_amounts.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/precise_wormhole.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/store_mainhand_coordinates.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/store_offhand_coordinates.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/crystals/blast_protection.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/crystals/fire_protection.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/crystals/projectile_protection.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/crystals/protection.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/flowers/check_poisonous_flowers.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/precursors/prismarine_shard.mcfunction
  gm4_zauber_cauldrons/pack.mcmeta
Labels: update
