Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2019-07, with the labels that each got.

#204 Update base: Check for updates whenever the player is targetable
  base/data/gm4/functions/init.mcfunction
  base/data/gm4/functions/load.mcfunction
  base/data/gm4/functions/out_of_date.mcfunction
  base/data/gm4/functions/tick.mcfunction
  base/data/gm4/functions/update.mcfunction
  base/data/minecraft/tags/functions/load.json
Labels: outdated, update

#256 Update enchantment extractors to 1.14
  gm4_enchantment_extractors/data/enchantment_extractors/functions/destroy.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/functions/enchantment.mcfunction
  gm4_enchantment_extractors/data/enchantment_extractors/loot_tables/destroy_enchantment_extractor.json
  gm4_enchantment_extractors/pack.mcmeta
Labels: tested, update

#198 Update Wormhole Bottles for 1.14
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/arrival_animation.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/choose_dimension.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/set_dimension.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/set_position.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/teleport_to_dimension.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/use_mainhand.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/cauldron/wormhole_targeting/use_offhand.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/init.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/init_check.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/main.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/extract_item_coordinates.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/store_coordinates.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/store_mainhand_coordinates.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/store_offhand_coordinates.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/loot_tables/check_consumed_bottle.json
  gm4_zauber_cauldrons/data/zauber_cauldrons/loot_tables/check_wormhole_bottle.json
  gm4_zauber_cauldrons/pack.mcmeta
Labels: needs feedback, update
