Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2019-09, with the labels that each got.

#292 Add translation namespaces everywhere
  gm4_cooler_caves/data/cooler_caves/functions/init.mcfunction
  gm4_dangerous_dungeons/data/dangerous_dungeons/functions/init.mcfunction
  gm4_liquid_tanks/data/gm4/advancements/liquid_tanks_create.json
  gm4_liquid_tanks/data/gm4/advancements/root.json
  gm4_liquid_tanks/data/gm4/advancements/standard_liquids.json
  gm4_liquid_tanks/data/liquid_tanks/functions/create.mcfunction
  gm4_liquid_tanks/data/liquid_tanks/functions/empty.mcfunction
  gm4_liquid_tanks/data/liquid_tanks/functions/init.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/level_report/100.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/level_report/300.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/level_report/experience.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/liquid_init/beetroot_soup.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/liquid_init/experience.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/liquid_init/lava.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/liquid_init/milk.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/liquid_init/mushroom_stew.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/liquid_init/rabbit_stew.mcfunction
  gm4_liquid_tanks/data/standard_liquids/functions/liquid_init/water.mcfunction
  gm4_mending_tanks/data/mending_tanks/functions/init.mcfunction
  gm4_orbis/data/orbis/functions/init.mcfunction
  gm4_potion_liquids/data/gm4/advancements/potion_liquids.json
  gm4_potion_liquids/data/gm4/advancements/root.json
  gm4_potion_liquids/data/potion_liquids/functions/init.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/item_fill/floating_potion.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/level_report/300.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/fire_resistance.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/floating.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/harming.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/healing.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/invisibility.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/leaping.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/luck.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/night_vision.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/poison.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/regeneration.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/slow_falling.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/slowness.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strength.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_harming.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_healing.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_leaping.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_poison.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_regeneration.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_slowness.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_strength.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_swiftness.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/strong_turtle_master.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/swiftness.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/turtle_master.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/water_breathing.mcfunction
  gm4_potion_liquids/data/potion_liquids/functions/liquid_init/weakness.mcfunction
  gm4_tower_structures/data/tower_structures/functions/init.mcfunction
Labels: improvement

#291 Update destroy_liquid_tank.json
  gm4_liquid_tanks/data/liquid_tanks/loot_tables/destroy_liquid_tank.json
Labels: fix, needs testing

#296 Small patch for vertical minecarts to make use of 1.14 features
  gm4_vertical_rails/data/vertical_rails/functions/main.mcfunction
  gm4_vertical_rails/data/vertical_rails/functions/pulse_check.mcfunction
  gm4_vertical_rails/data/vertical_rails/tags/entity_types/minecart.json
Labels: improvement, needs testing

#279 Add string recipes
  gm4_standard_crafting/data/standard_crafting/functions/recipe_check.mcfunction
  gm4_standard_crafting/data/standard_crafting/functions/string_recipes.mcfunction
Labels: tested, update

#259 Moneo Shamir
  gm4_moneo_shamir/data/gm4/tags/functions/init_check.json
  gm4_moneo_shamir/data/gm4/tags/functions/pulse_check.json
  gm4_moneo_shamir/data/metallurgy/tags/functions/check_item_validity.json
  gm4_moneo_shamir/data/metallurgy/tags/functions/summon_band/aluminium.json
  gm4_moneo_shamir/data/moneo_shamir/functions/active.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/check_item_validity.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/expansion/init.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/expansion/init_check.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/expansion/main.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/expansion/pulse_check.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/mark_item_validity.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/store_maximum.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/summon_band.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/tools/materials/diamond.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/tools/materials/gold.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/tools/materials/iron.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/tools/materials/stone.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/tools/materials/wood.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/tools/shears.mcfunction
  gm4_moneo_shamir/pack.mcmeta
Labels: module, submission, tested

#302 Add custom NBT to tier IV potions
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/instant_damage.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/instant_health.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/jump_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/poison.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/regeneration.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/speed.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/strength.mcfunction
Labels: improvement, tested

#303 Add Zauber Liquids
  gm4_zauber_liquids/data/gm4/tags/functions/init_check.json
  gm4_zauber_liquids/data/liquid_tanks/tags/functions/item_drain.json
  gm4_zauber_liquids/data/liquid_tanks/tags/functions/item_fill.json
  gm4_zauber_liquids/data/liquid_tanks/tags/functions/remove_liquid_tags.json
  gm4_zauber_liquids/data/liquid_tanks/tags/functions/tank_init.json
  gm4_zauber_liquids/data/liquid_tanks/tags/functions/util_below.json
  gm4_zauber_liquids/data/zauber_liquids/functions/init.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/init_check.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_drain/item_drain.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_drain/zauber_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/item_fill.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/zauber_harming_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/zauber_healing_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/zauber_leaping_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/zauber_poison_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/zauber_regeneration_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/zauber_strength_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/item_fill/zauber_swiftness_potion.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/liquid_init/harming.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/liquid_init/healing.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/liquid_init/leaping.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/liquid_init/poison.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/liquid_init/regeneration.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/liquid_init/strength.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/liquid_init/swiftness.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/remove_liquid_tags.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/tank_init.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util/harming.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util/healing.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util/leaping.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util/poison.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util/regeneration.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util/strength.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util/swiftness.mcfunction
  gm4_zauber_liquids/data/zauber_liquids/functions/util_below.mcfunction
  gm4_zauber_liquids/pack.mcmeta
Labels: module, tested
