Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2019-12, with the labels that each got.

#277 Change order of checks in decompress functions to fix NBT loss
  gm4_block_compressors/data/block_compressors/functions/decompress/16.mcfunction
  gm4_block_compressors/data/block_compressors/functions/decompress/64.mcfunction
Labels: fix, tested

#326 Improved lag in detecting if a player has boots of ostara
  gm4_boots_of_ostara/data/boots_of_ostara/advancements/enable_boots.json
  gm4_boots_of_ostara/data/boots_of_ostara/functions/active.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/enable_boots.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/main.mcfunction
Labels: improvement, tested

#313 Added Quartz Block > 4x Nether Quartz recipe (STANDARD CRAFTING)
  gm4_standard_crafting/data/standard_crafting/functions/recipe_check.mcfunction
Labels: update

#308 Moneo Spigot Fix
  gm4_moneo_shamir/data/moneo_shamir/functions/active.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/expansion/main.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/expansion/pulse_check.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/item_check.mcfunction
  gm4_moneo_shamir/data/moneo_shamir/functions/store_maximum.mcfunction
Labels: fix, tested

#307 Fix Malachite Lump skull repairing CMD
  gm4_metallurgy/data/metallurgy/functions/repair_skulls.mcfunction
Labels: fix

#305 Fixed edge case
  gm4_ambrosia/data/ambrosia/functions/hive/find_flowers.mcfunction
Labels: fix

#315 Crossbow Cartridges
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/check_projectile.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/init.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/init_check.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/main.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/arrow_motion.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/fireball.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/fish/cod.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/fish/pufferfish.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/fish/salmon.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/fish/tropical.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/lingerpotion.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/splashpotion.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/projectile/torch.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/pulse_check.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/torch/torch_check.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/functions/torch/torch_place.mcfunction
  gm4_crossbow_cartridges/data/crossbow_cartridges/tags/blocks/dirty.json
  gm4_crossbow_cartridges/data/crossbow_cartridges/tags/blocks/replaceable.json
  gm4_crossbow_cartridges/data/crossbow_cartridges/tags/blocks/torch.json
  gm4_crossbow_cartridges/data/crossbow_cartridges/tags/blocks/torch_placeable.json
  gm4_crossbow_cartridges/data/gm4/advancements/crossbow_cartridges_fish.json
  gm4_crossbow_cartridges/data/gm4/advancements/crossbow_cartridges_use.json
  gm4_crossbow_cartridges/data/gm4/advancements/root.json
  gm4_crossbow_cartridges/data/gm4/tags/functions/init_check.json
  gm4_crossbow_cartridges/data/gm4/tags/functions/pulse_check.json
  gm4_crossbow_cartridges/pack.mcmeta
Labels: needs feedback, submission

#266 Add Relocators
  gm4_relocators/data/custom_crafters/tags/functions/recipe_check.json
  gm4_relocators/data/gm4/advancements/relocators.json
  gm4_relocators/data/gm4/advancements/root.json
  gm4_relocators/data/gm4/tags/functions/init_check.json
  gm4_relocators/data/relocators/advancements/place_relocated_block.json
  gm4_relocators/data/relocators/advancements/place_relocator.json
  gm4_relocators/data/relocators/advancements/place_relocator_wall.json
  gm4_relocators/data/relocators/functions/check_block_items.mcfunction
  gm4_relocators/data/relocators/functions/check_machine_block.mcfunction
  gm4_relocators/data/relocators/functions/check_machine_block_wall.mcfunction
  gm4_relocators/data/relocators/functions/found_machine.mcfunction
  gm4_relocators/data/relocators/functions/init.mcfunction
  gm4_relocators/data/relocators/functions/init_check.mcfunction
  gm4_relocators/data/relocators/functions/placed_machine_block.mcfunction
  gm4_relocators/data/relocators/functions/ray.mcfunction
  gm4_relocators/data/relocators/functions/recipe_check.mcfunction
  gm4_relocators/data/relocators/functions/relocating_ray.mcfunction
  gm4_relocators/data/relocators/functions/set_machine_data.mcfunction
  gm4_relocators/data/relocators/functions/store_machine_data.mcfunction
  gm4_relocators/data/relocators/tags/blocks/air.json
  gm4_relocators/pack.mcmeta
Labels: module, submission

#349 Add snow particle
  gm4_particles_pack/data/gm4_particles_pack/functions/apply_book.mcfunction
  gm4_particles_pack/data/gm4_particles_pack/functions/particle.mcfunction
Labels: tested, update

#350 Ver/1.14 Add Snow Particle
  gm4_particles_pack/data/particles_pack/functions/apply_book.mcfunction
  gm4_particles_pack/data/particles_pack/functions/particle.mcfunction
Labels: update
