Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2019-08, with the labels that each got.

#267 Bats now no longer explode when they are defused
  gm4_bat_grenades/data/bat_grenades/functions/main.mcfunction
Labels: fix, tested

#242 Add Holographic Tags
  gm4_holographic_tags/data/gm4/advancements/holographic_tags.json
  gm4_holographic_tags/data/gm4/advancements/root.json
  gm4_holographic_tags/data/gm4/tags/functions/init_check.json
  gm4_holographic_tags/data/gm4/tags/functions/pulse_check.json
  gm4_holographic_tags/data/holographic_tags/functions/create_hologram.mcfunction
  gm4_holographic_tags/data/holographic_tags/functions/destroy_hologram.mcfunction
  gm4_holographic_tags/data/holographic_tags/functions/init.mcfunction
  gm4_holographic_tags/data/holographic_tags/functions/init_check.mcfunction
  gm4_holographic_tags/data/holographic_tags/functions/main.mcfunction
  gm4_holographic_tags/data/holographic_tags/functions/pulse_check.mcfunction
  gm4_holographic_tags/data/holographic_tags/functions/set_color.mcfunction
  gm4_holographic_tags/pack.mcmeta
Labels: module, submission, tested

#221 Add Liquid Minecarts
  gm4_liquid_minecarts/data/gm4/tags/functions/init_check.json
  gm4_liquid_minecarts/data/gm4/tags/functions/pulse_check.json
  gm4_liquid_minecarts/data/liquid_minecarts/functions/compare_load_liquid.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/compare_unload_liquid.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/create.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/destroy.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/drain_minecart.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/init.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/init_check.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/init_liquid.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/init_tank.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/level_report.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/level_report_ray.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/liquid_value_update.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/load_check.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/load_liquid.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/main.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/minecart_to_tank_init.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/pulse_check.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/try_to_load.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/try_to_unload.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/functions/unload_liquid.mcfunction
  gm4_liquid_minecarts/data/liquid_minecarts/loot_tables/destroy_liquid_minecart.json
  gm4_liquid_minecarts/pack.mcmeta
Labels: tested

#276 Update Cement Mixers to 1.14
  gm4_cement_mixers/data/cement_mixers/functions/init.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/init_check.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/black_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/blue_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/brown_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/cyan_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/gray_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/green_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/light_blue_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/light_gray_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/lime_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/magenta_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/orange_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/pink_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/purple_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/red_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/white_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/yellow_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/water_concrete.mcfunction
  gm4_cement_mixers/data/gm4/advancements/root.json
  gm4_cement_mixers/data/gm4/tags/functions/init_check.json
  gm4_cement_mixers/data/liquid_tanks/tags/functions/item_fill.json
  gm4_cement_mixers/pack.mcmeta
Labels: update

#275 Change better armourstands invisibility
  gm4_better_armour_stands/data/better_armour_stands/functions/apply_book.mcfunction
Labels: tested, update
