Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2019-05, with the labels that each got.

#167 Added cement mixer
  gm4_cement_mixers/data/cement_mixers/functions/init.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/init_check.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/black_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/blue_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/brown_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/cyan_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/gray_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/green_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/light_blue_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/light_gray_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/lime_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/magenta_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/orange_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/pink_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/purple_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/red_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/white_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/item_fill/yellow_concrete.mcfunction
  gm4_cement_mixers/data/cement_mixers/functions/water_concrete.mcfunction
  gm4_cement_mixers/data/gm4/advancements/root.json
  gm4_cement_mixers/data/gm4/tags/functions/init_check.json
  gm4_cement_mixers/data/liquid_tanks/tags/functions/item_fill.json
  gm4_cement_mixers/pack.mcmeta
Labels: module, needs feedback, needs testing

#197 Update Chairs 1.14
  gm4_chairs/data/chairs/functions/correction.mcfunction
  gm4_chairs/data/chairs/functions/kill.mcfunction
  gm4_chairs/data/chairs/functions/main.mcfunction
  gm4_chairs/data/chairs/functions/saddle.mcfunction
  gm4_chairs/data/chairs/loot_tables/drop_saddle.json
Labels: update

#199 Update Trapped Signs to 1.14
  gm4_trapped_signs/data/trapped_signs/advancements/place_secret_trapped_sign.json
  gm4_trapped_signs/data/trapped_signs/advancements/place_trapped_sign.json
  gm4_trapped_signs/data/trapped_signs/functions/activate.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/complete.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/create.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/deactivate.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/destroy.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/init.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/main.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/place_secret_trapped_sign.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/place_sign.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/place_trapped_sign.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/process.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/pulse.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/pulse_check.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/ray.mcfunction
  gm4_trapped_signs/data/trapped_signs/functions/recipe_check.mcfunction
  gm4_trapped_signs/data/trapped_signs/tags/blocks/signs.json
  gm4_trapped_signs/pack.mcmeta
Labels: needs feedback, update

#184 Update Sunken Treasure to 1.14
  gm4_sunken_treasure/data/gm4/advancements/sunken_treasure.json
  gm4_sunken_treasure/data/sunken_treasure/functions/check_treasure.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/functions/init.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/functions/pulse_check.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/functions/spawn_treasure.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/function/treasure_type.json
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/item_treasure.json
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/item_treasure/base.json
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/item_treasure/scuba.json
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/item_treasure/shared.json
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/item_treasure_scuba.json
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/treasure_chest.json
  gm4_sunken_treasure/pack.mcmeta
Labels: needs testing, update
