Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2019-04, with the labels that each got.

#151 Release Spawner Minecarts
  gm4_spawner_minecarts/data/gm4/functions/init.mcfunction
  gm4_spawner_minecarts/data/gm4/functions/tick.mcfunction
  gm4_spawner_minecarts/data/gm4/functions/update.mcfunction
  gm4_spawner_minecarts/data/minecraft/tags/functions/load.json
  gm4_spawner_minecarts/data/minecraft/tags/functions/tick.json
  gm4_spawner_minecarts/data/spawner_minecarts/functions/capture_spawner/finalize_enter_minecart.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/capture_spawner/spawner_list.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/fuel/active_regeneration.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/fuel/consume_grass.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/fuel/consume_normal_flower.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/fuel/consume_poisonous_flower.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/fuel/passive_regeneration.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/fuel/rail_checks.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/fuel/unloaded_fuel_calculations.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/init.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/init_check.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/main.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/pulse_check.mcfunction
  gm4_spawner_minecarts/data/spawner_minecarts/functions/spawning/spawn_detection.mcfunction
Labels: module

#117 New module: SCUBA Gear
  gm4_scuba_gear/data/custom_crafters/tags/functions/recipe_check.json
  gm4_scuba_gear/data/gm4/advancements/root.json
  gm4_scuba_gear/data/gm4/advancements/scuba_gear.json
  gm4_scuba_gear/data/gm4/tags/functions/init_check.json
  gm4_scuba_gear/data/gm4/tags/functions/pulse_check.json
  gm4_scuba_gear/data/scuba_gear/functions/breathe.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/check_gear.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/equipped.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/init.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/init_check.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/main.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/pulse_check.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/recipe_check.mcfunction
  gm4_scuba_gear/data/scuba_gear/functions/remove_effect.mcfunction
  gm4_scuba_gear/data/scuba_gear/tags/blocks/seagrass.json
  gm4_scuba_gear/data/scuba_gear/tags/blocks/water_loggable.json
  gm4_scuba_gear/pack.mcmeta
Labels: needs feedback, submission

#150 Chairs
  gm4_chairs/data/chairs/functions/correction.mcfunction
  gm4_chairs/data/chairs/functions/init.mcfunction
  gm4_chairs/data/chairs/functions/init_check.mcfunction
  gm4_chairs/data/chairs/functions/kill.mcfunction
  gm4_chairs/data/chairs/functions/main.mcfunction
  gm4_chairs/data/chairs/functions/pulse_check.mcfunction
  gm4_chairs/data/chairs/functions/saddle.mcfunction
  gm4_chairs/data/gm4/advancements/chairs_creation.json
  gm4_chairs/data/gm4/advancements/chairs_sit.json
  gm4_chairs/data/gm4/advancements/root.json
  gm4_chairs/data/gm4/tags/functions/init_check.json
  gm4_chairs/data/gm4/tags/functions/pulse_check.json
  gm4_chairs/pack.mcmeta
Labels: needs feedback, submission

#49 New Module: Note Block Interface
  gm4_note_block_interface/data/gm4/tags/functions/init_check.json
  gm4_note_block_interface/data/gm4/tags/functions/pulse_check.json
  gm4_note_block_interface/data/note_block_interface/functions/click/loop.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/click/setup.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/click/sneak_loop.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/init.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/init_check.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/interface/change.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/interface/create.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/pulse_check.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/punch/loop.mcfunction
  gm4_note_block_interface/data/note_block_interface/functions/punch/setup.mcfunction
  gm4_note_block_interface/pack.mcmeta
Labels: module, needs feedback, submission

#153 Allow Pig Tractors to plant netherwart
  gm4_pig_tractors/data/pig_tractors/functions/check_crop.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/choose_netherwart.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/has_hoe.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/place_crops/nether_wart.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/replace_crops/nether_wart.mcfunction
  gm4_pig_tractors/data/pig_tractors/tags/blocks/crops.json
Labels: tested, update

#125 Add Disassemblers
  gm4_disassemblers/data/custom_crafters/tags/functions/recipe_check.json
  gm4_disassemblers/data/disassemblers/functions/calculate_percent.mcfunction
  gm4_disassemblers/data/disassemblers/functions/check_disassemble_recipe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/check_dropper.mcfunction
  gm4_disassemblers/data/disassemblers/functions/init.mcfunction
  gm4_disassemblers/data/disassemblers/functions/init_check.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_axe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_boots.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_chestplate.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_helmet.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_hoe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_leggings.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_pickaxe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_shovel.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/diamond_sword.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/flint_and_steel.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_axe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_boots.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_chestplate.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_helmet.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_hoe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_leggings.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_pickaxe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_shovel.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/golden_sword.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_axe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_boots.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_chestplate.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_helmet.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_hoe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_leggings.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_pickaxe.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_shovel.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/iron_sword.mcfunction
  gm4_disassemblers/data/disassemblers/functions/items/shears.mcfunction
  gm4_disassemblers/data/disassemblers/functions/kill.mcfunction
  gm4_disassemblers/data/disassemblers/functions/main.mcfunction
  gm4_disassemblers/data/disassemblers/functions/pulse_check.mcfunction
  gm4_disassemblers/data/disassemblers/functions/random.mcfunction
  gm4_disassemblers/data/disassemblers/functions/recipe_check.mcfunction
  gm4_disassemblers/data/disassemblers/functions/spawn.mcfunction
  gm4_disassemblers/data/disassemblers/functions/update.mcfunction
  gm4_disassemblers/data/disassemblers/tags/functions/check_recipe.json
  gm4_disassemblers/data/gm4/advancements/disassemblers.json
  gm4_disassemblers/data/gm4/advancements/disassembling.json
  gm4_disassemblers/data/gm4/advancements/root.json
  gm4_disassemblers/data/gm4/tags/functions/init_check.json
  gm4_disassemblers/data/gm4/tags/functions/pulse_check.json
  gm4_disassemblers/pack.mcmeta
Labels: module, needs feedback, needs testing

#136 [Desire Lines] Added new advancements
  gm4_desire_lines/data/desire_lines/functions/init.mcfunction
  gm4_desire_lines/data/desire_lines/functions/path.mcfunction
  gm4_desire_lines/data/desire_lines/functions/pulse_check.mcfunction
  gm4_desire_lines/data/gm4/advancements/desire_lines_10000.json
  gm4_desire_lines/data/gm4/advancements/desire_lines_8000.json
  gm4_desire_lines/data/gm4/advancements/root.json
Labels: needs feedback, needs testing, update

#138 Added Invisible and Visible Tags
  gm4_better_armour_stands/data/better_armour_stands/functions/apply_book.mcfunction
  gm4_better_armour_stands/data/better_armour_stands/functions/main.mcfunction
  gm4_particles_pack/data/particles_pack/functions/main.mcfunction
Labels: module, needs feedback, needs testing

#147 Sunken Treasure
  gm4_sunken_treasure/data/gm4/advancements/root.json
  gm4_sunken_treasure/data/gm4/advancements/sunken_treasure.json
  gm4_sunken_treasure/data/gm4/tags/functions/init_check.json
  gm4_sunken_treasure/data/gm4/tags/functions/pulse_check.json
  gm4_sunken_treasure/data/sunken_treasure/functions/check_treasure.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/functions/init.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/functions/init_check.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/functions/pulse_check.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/functions/spawn_treasure.mcfunction
  gm4_sunken_treasure/data/sunken_treasure/loot_tables/treasure_chest.json
  gm4_sunken_treasure/pack.mcmeta
Labels: module, needs feedback, needs testing

#159 Mysterious Midnights
  gm4_mysterious_midnights/data/falling_stars/functions/event.mcfunction
  gm4_mysterious_midnights/data/falling_stars/functions/find_location.mcfunction
  gm4_mysterious_midnights/data/falling_stars/functions/hatch_endermite.mcfunction
  gm4_mysterious_midnights/data/falling_stars/functions/setup.mcfunction
  gm4_mysterious_midnights/data/falling_stars/functions/spawn_falling_star.mcfunction
  gm4_mysterious_midnights/data/gm4/advancements/mysterious_midnights.json
  gm4_mysterious_midnights/data/gm4/advancements/root.json
  gm4_mysterious_midnights/data/gm4/tags/functions/init_check.json
  gm4_mysterious_midnights/data/gm4/tags/functions/pulse_check.json
  gm4_mysterious_midnights/data/harvest_moons/functions/dawn_active_check.mcfunction
  gm4_mysterious_midnights/data/harvest_moons/functions/dawn_event.mcfunction
  gm4_mysterious_midnights/data/harvest_moons/functions/event.mcfunction
  gm4_mysterious_midnights/data/harvest_moons/functions/setup.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/calculate_moon_phase.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/expansion_selection/calculate_midnight_difficulty.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/expansion_selection/included_expansions.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/expansion_selection/start_expansion.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/init.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/init_check.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/main.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/pulse_check.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/send_night_end_pulse.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/tags/functions/common_expansion.json
  gm4_mysterious_midnights/data/mysterious_midnights/tags/functions/dawn_event.json
  gm4_mysterious_midnights/data/mysterious_midnights/tags/functions/rare_expansion.json
  gm4_mysterious_midnights/data/mysterious_midnights/tags/functions/uncommon_expansion.json
  gm4_mysterious_midnights/data/nightmare_nights/functions/dawn_active_check.mcfunction
  gm4_mysterious_midnights/data/nightmare_nights/functions/dawn_event.mcfunction
  gm4_mysterious_midnights/data/nightmare_nights/functions/event.mcfunction
  gm4_mysterious_midnights/data/nightmare_nights/functions/initialise.mcfunction
  gm4_mysterious_midnights/data/nightmare_nights/functions/setup.mcfunction
  gm4_mysterious_midnights/data/nightmare_nights/tags/functions/nightmare_night_expansion.json
  gm4_mysterious_midnights/data/resurrecting_skeletons/functions/absorb_bone.mcfunction
  gm4_mysterious_midnights/data/resurrecting_skeletons/functions/event.mcfunction
  gm4_mysterious_midnights/data/resurrecting_skeletons/functions/mark_bone.mcfunction
  gm4_mysterious_midnights/data/resurrecting_skeletons/functions/setup.mcfunction
  gm4_mysterious_midnights/data/resurrecting_skeletons/functions/spawn_skeleton.mcfunction
  gm4_mysterious_midnights/data/resurrecting_zombies/functions/absorb_rotten_flesh.mcfunction
  gm4_mysterious_midnights/data/resurrecting_zombies/functions/event.mcfunction
  gm4_mysterious_midnights/data/resurrecting_zombies/functions/mark_rotten_flesh.mcfunction
  gm4_mysterious_midnights/data/resurrecting_zombies/functions/setup.mcfunction
  gm4_mysterious_midnights/data/resurrecting_zombies/functions/spawn_zombie.mcfunction
  gm4_mysterious_midnights/data/tipped_skeletons/functions/event.mcfunction
  gm4_mysterious_midnights/data/tipped_skeletons/functions/setup.mcfunction
  gm4_mysterious_midnights/data/tipped_skeletons/functions/tipp.mcfunction
  gm4_mysterious_midnights/pack.mcmeta
Labels: module, tested

#163 Increase Likelyhood of Mysterious Midnights
  gm4_mysterious_midnights/data/mysterious_midnights/functions/expansion_selection/calculate_midnight_difficulty.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/expansion_selection/start_expansion.mcfunction
  gm4_mysterious_midnights/data/mysterious_midnights/functions/send_night_end_pulse.mcfunction
Labels: fix, tested

#180 Fix #149 - Cave air and void air not handled like air
  gm4_boots_of_ostara/data/boots_of_ostara/functions/active.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/functions/recipe_check.mcfunction
  gm4_boots_of_ostara/data/boots_of_ostara/tags/blocks/air.json
  gm4_phantom_scarecrows/data/phantom_scarecrows/tags/blocks/traversable.json
  gm4_pig_tractors/data/gm4/tags/functions/init_check.json
  gm4_pig_tractors/data/gm4/tags/functions/pulse_check.json
  gm4_pig_tractors/data/pig_tractors/functions/check_inventory.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/choose_crop.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/choose_netherwart.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/has_hoe.mcfunction
  gm4_pig_tractors/data/pig_tractors/functions/pulse_check.mcfunction
  gm4_pig_tractors/data/pig_tractors/tags/blocks/air.json
  gm4_pig_tractors/data/pig_tractors/tags/blocks/crop_age7.json
  gm4_pig_tractors/data/pig_tractors/tags/blocks/crops.json
  gm4_pig_tractors/data/pig_tractors/tags/blocks/tillable.json
  gm4_shroomites/data/shroomites/tags/blocks/shroom_rootable.json
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/poison.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/strength.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/tags/blocks/air.json
Labels: fix, needs feedback

#176 Update base
  base/data/gm4/functions/init.mcfunction
  base/data/gm4/functions/out_of_date.mcfunction
  base/data/gm4/functions/tick.mcfunction
  base/data/gm4/functions/update.mcfunction
  base/data/minecraft/tags/functions/load.json
  base/data/minecraft/tags/functions/tick.json
  base/pack.mcmeta
Labels: update

#185 Zauber Cauldrons 1.14
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/main.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/boots/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/boots/health_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/boots/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/boots/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/chestplate/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/chestplate/health_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/chestplate/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/chestplate/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/helmet/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/helmet/health_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/helmet/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/helmet/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/leggings/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/leggings/health_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/leggings/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/armor/leggings/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/chorus/store_offhand_coordinates.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/flowers/initiate_flower_types.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/instant_damage.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/instant_health.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/jump_boost.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/poison.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/regeneration.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/speed.mcfunction
  gm4_zauber_cauldrons/data/zauber_cauldrons/functions/recipes/potions/strength.mcfunction
Labels: module, tested, update

#4 Add sweethearts module
  gm4_sweethearts/data/gm4/advancements/root.json
  gm4_sweethearts/data/gm4/advancements/sweethearts_selfless.json
  gm4_sweethearts/data/gm4/tags/functions/init_check.json
  gm4_sweethearts/data/gm4/tags/functions/pulse_check.json
  gm4_sweethearts/data/sweethearts/functions/init.mcfunction
  gm4_sweethearts/data/sweethearts/functions/init_check.mcfunction
  gm4_sweethearts/data/sweethearts/functions/main.mcfunction
  gm4_sweethearts/data/sweethearts/functions/pulse_check.mcfunction
  gm4_sweethearts/data/sweethearts/functions/sneaking.mcfunction
  gm4_sweethearts/data/sweethearts/functions/transfer.mcfunction
  gm4_sweethearts/pack.mcmeta
Labels: module, needs testing
