Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2020-09, with the labels that each got.

#467 1.16 potion bug fix
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/projectile/lingerpotion.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/projectile/splashpotion.mcfunction
Labels: fix

#446 Add Soul Speed to Enchantment Extractors
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/check.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/soul_speed.json
Labels: feature-update

#454 Better armour stands fix
  gm4_better_armour_stands/data/gm4_better_armour_stands/functions/apply_book.mcfunction
Labels: fix, tested

#472 Center Wormhole TNT on player
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/player/wormhole_targeting/set_dimension.mcfunction
Labels: quality-update, tested

#465 [Metallurgy] Added new 1.16 items
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/main.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_defuse_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_forterra_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_gemini_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_hypexperia_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_levity_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/init.mcfunction
  gm4_metallurgy/data/gm4_musical_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_nether/ancient_debris.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_nether/nether_gold_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_nether/nether_quartz_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_overworld/coal_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_overworld/diamond_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_overworld/emerald_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_overworld/gold_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_overworld/iron_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_overworld/lapis_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/mark_overworld/redstone_ore.mcfunction
  gm4_metallurgy/data/gm4_sensus_shamir/functions/block_search/search.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/active.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/netherite_ingot.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/pickaxe.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/mark_item_validity.mcfunction
Labels: feature-update, server-testing

#474 Fix adding shamirs on items with Custom Model Data
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/add_band/found_item.mcfunction
Labels: fix
