Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2020-03, with the labels that each got.

#371 Add Soul Glass
  gm4_soul_glass/data/gm4/advancements/root.json
  gm4_soul_glass/data/gm4/advancements/soul_glass.json
  gm4_soul_glass/data/gm4_soul_glass/advancements/place_blast_furnace.json
  gm4_soul_glass/data/gm4_soul_glass/advancements/place_soul_glass.json
  gm4_soul_glass/data/gm4_soul_glass/functions/beacon_clock.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/destroy.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/apply_normal_effect.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/apply_strong_effect.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/check.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_1.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_1_strong.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_2.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_2_strong.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_3.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_3_strong.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_4.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_4_strong.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/revert_effects.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/update_effects.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/check_finish_smelt.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/finish_smelt.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/modify_output.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/place_blast_furnace.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/prep_finish_smelt.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/process.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/ray.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/smelting.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/init.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/load.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/main.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/place_soul_glass.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/process.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/ray.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/predicates/has_beam.json
  gm4_soul_glass/data/gm4_soul_glass/tags/blocks/beacon_passable.json
  gm4_soul_glass/data/gm4_soul_glass/tags/blocks/piston.json
  gm4_soul_glass/data/load/tags/functions/gm4_soul_glass.json
  gm4_soul_glass/data/load/tags/functions/load.json
  gm4_soul_glass/data/minecraft/recipes/soul_glass.json
  gm4_soul_glass/pack.mcmeta
Labels: module

#380 Update Master Crafting Recipes
  gm4_master_crafting/data/gm4_custom_crafters/tags/functions/recipe_check.json
  gm4_master_crafting/data/gm4_master_crafting/functions/master_recipe_check.mcfunction
  gm4_master_crafting/data/gm4_master_crafting/functions/recipes/block_recipes.mcfunction
  gm4_master_crafting/data/gm4_master_crafting/functions/recipes/brick_recipes.mcfunction
  gm4_master_crafting/data/gm4_master_crafting/functions/recipes/liquid_recipes.mcfunction
  gm4_master_crafting/data/gm4_master_crafting/functions/recipes/master_recipe_check.mcfunction
  gm4_master_crafting/data/gm4_master_crafting/functions/recipes/recipe_check.mcfunction
  gm4_master_crafting/data/gm4_master_crafting/tags/functions/recipe_check.json
Labels: fix, tested, update

#382 Add Advancement to Record Crafting
  gm4_record_crafting/data/gm4/advancements/record_crafting.json
  gm4_record_crafting/data/gm4_record_crafting/functions/recipe_check.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/11.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/13.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/blocks.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/cat.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/chirp.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/far.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/mall.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/mellohi.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/stal.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/strad.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/wait.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/functions/recipes/ward.mcfunction
Labels: tested, update

#374 Add 1.15 Tunnel Bores
  gm4_tunnel_bores/data/gm4/advancements/root.json
  gm4_tunnel_bores/data/gm4/advancements/tunnel_bores.json
  gm4_tunnel_bores/data/gm4_custom_crafters/tags/functions/recipe_check.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/activator_rail/force_mine.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/check_cart_environment.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/create.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/destroy.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/restore_previous_direction.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/store_push_east_west.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/store_push_north_south.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_direction.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_rotation.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/fuel/check_fuel_level.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/fuel/found_charcoal.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/fuel/found_coal.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/fuel/found_supply_cart.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/fuel/load_charcoal.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/fuel/load_coal.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/fuel/search_fuel.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/rail/check_solidity.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/rail/found_rail.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/rail/found_supply_cart.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/rail/handle_rail.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/rail/load_rail.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/rail/place_rail.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/mine/auto_mine.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/mine/break_block.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/mine/cooldown/calculate_clock_timings.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/mine/cooldown/clock_control.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/mine/stop_cart.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/tunnel_bore_5hz.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/furnace_cart_20hz.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/init.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/load.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/main.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/mc_51053.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/pulse_check.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/recipe_check.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/loot_tables/bore.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/tags/blocks/air.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/tags/blocks/liquids.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/tags/blocks/not_rail_solid.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/tags/blocks/unbreakable.json
  gm4_tunnel_bores/data/load/tags/functions/gm4_tunnel_bores.json
  gm4_tunnel_bores/data/load/tags/functions/load.json
  gm4_tunnel_bores/pack.mcmeta
Labels: module, needs testing
