Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2020-08, with the labels that each got.

#294 [Update] Smelteries (formerly Blast Furnaces)
  gm4_smelteries/data/gm4/advancements/root.json
  gm4_smelteries/data/gm4/advancements/smelteries.json
  gm4_smelteries/data/gm4_custom_crafters/tags/functions/recipe_check.json
  gm4_smelteries/data/gm4_smelteries/functions/check_ore.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/create.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/destroy.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/find_furnace.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/init.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/limited_tick.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/load.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/main.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/process.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/recipe_check.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/smelt.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/start_ticking.mcfunction
  gm4_smelteries/data/gm4_smelteries/functions/verify_furnace.mcfunction
  gm4_smelteries/data/gm4_smelteries/loot_tables/destroy_smeltery.json
  gm4_smelteries/data/gm4_smelteries/loot_tables/smelt.json
  gm4_smelteries/data/gm4_smelteries/loot_tables/smeltable_display.json
  gm4_smelteries/data/gm4_smelteries/tags/blocks/air.json
  gm4_smelteries/data/load/tags/functions/gm4_smelteries.json
  gm4_smelteries/data/load/tags/functions/load.json
  gm4_smelteries/pack.mcmeta
Labels: module, needs feedback, server testing

#362 TNT landmines for 1.15
  gm4_tnt_landmines/data/gm4/advancements/root.json
  gm4_tnt_landmines/data/gm4/advancements/tnt_landmines.json
  gm4_tnt_landmines/data/gm4_custom_crafters/tags/functions/recipe_check.json
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/blowup/explosive.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/blowup/safe.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/blowup/type_check.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/checks/blowup.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/checks/creation.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/checks/landmine.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/fix_skull.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/init.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/items/create.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/items/disarming.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/items/upgrade.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/load.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/main.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/recipe_check.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/tick.mcfunction
  gm4_tnt_landmines/data/load/tags/functions/gm4_tnt_landmines.json
  gm4_tnt_landmines/data/load/tags/functions/load.json
  gm4_tnt_landmines/pack.mcmeta
Labels: module, update

#376 Add beehive inspector
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/init.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/inspect.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/load.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/main.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/loot_tables/lore.json
  gm4_beehive_inspector/data/load/tags/functions/gm4_beehive_inspector.json
  gm4_beehive_inspector/data/load/tags/functions/load.json
  gm4_beehive_inspector/pack.mcmeta
Labels: module, server testing, submission

#402 Add Fulcio Shamir
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/4_tick.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/active.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/check_item_validity.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/create_block.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/init.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/load.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/main.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/mark_item_validity.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/particles.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/process_block.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/summon_band.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/loot_tables/band.json
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/predicates/holding_fulcio.json
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/tags/blocks/air.json
  gm4_fulcio_shamir/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_fulcio_shamir/data/gm4_metallurgy/tags/functions/summon_band/barimium.json
  gm4_fulcio_shamir/data/load/tags/functions/gm4_fulcio_shamir.json
  gm4_fulcio_shamir/data/load/tags/functions/gm4_metallurgy.json
  gm4_fulcio_shamir/data/load/tags/functions/load.json
  gm4_fulcio_shamir/pack.mcmeta
Labels: module, server testing, submission

#406 Merged Roped Arrows into Crossbow Cartridges
  gm4_crossbow_cartridges/data/gm4/advancements/crossbow_cartridges_fish.json
  gm4_crossbow_cartridges/data/gm4/advancements/crossbow_cartridges_string.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/determine_direction.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/place_string.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/shoot_arrow.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/unspool_string_east.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/unspool_string_north.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/unspool_string_south.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/unspool_string_west.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/check_projectile.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/init.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/load.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/projectile/arrow_motion.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/projectile/torch.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/torch/torch_check.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/torch/torch_loop.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/torch/torch_place.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/loot_tables/drop_torch.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/check_block_x-.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/check_block_x.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/check_block_y.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/check_block_z-.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/check_block_z.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/cod.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/fire_charge.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/lingering_potion.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/pufferfish.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/salmon.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/splash_potion.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/string.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/torch.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/tropical.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/tags/blocks/dirty.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/tags/blocks/string_replaceable.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/tags/blocks/torch_placeable.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/tags/blocks/torch_placeable_top.json
  gm4_crossbow_cartridges/pack.mcmeta
Labels: update

#415 Better Armorstands Poses pack redesign/upgrade
  gm4_poses_pack/data/gm4/advancements/poses_changed.json
  gm4_poses_pack/data/gm4_poses_pack/functions/apply_book.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/copy.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/init.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/arms.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/body.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/head.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/legs.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/arm_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/arm_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/body.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/flip_arms.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/flip_legs.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/head.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/leg_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/leg_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_arm_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_arm_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_leg_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_leg_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/swap_arms.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/swap_legs.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/update_values.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose_changed.mcfunction
  gm4_poses_pack/pack.mcmeta
Labels: improvement, update

#436 Update Enchantment Extractors
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/enchantment.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/extract.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/extract_binding.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/extract_failed.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/extract_vanishing.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/init.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/next_random.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/process.mcfunction
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/aqua_affinity.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/bane_of_arthropods.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/binding_curse.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/blast_protection.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/channeling.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/check.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/depth_strider.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/efficiency.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/feather_falling.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/fire_aspect.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/fire_protection.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/flame.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/fortune.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/frost_walker.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/impaling.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/infinity.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/knockback.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/looting.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/loyalty.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/luck_of_the_sea.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/lure.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/mending.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/multishot.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/piercing.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/power.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/projectile_protection.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/protection.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/punch.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/quick_charge.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/respiration.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/riptide.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/sharpness.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/silk_touch.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/smite.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/sweeping.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/thorns.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/unbreaking.json
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/loot_tables/extract/vanishing_curse.json
  gm4_enchantment_extractors/pack.mcmeta
Labels: improvement

#439 Add CustomModelData to Obsidian Casts
  gm4_lumos_shamir/data/gm4_lumos_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_arborenda_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_conduction_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_defuse_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_ender_bolt_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_forterra_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_gemini_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_hypexperia_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_levity_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/add_band/check.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/add_band/found_item.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/remove_band/finish_item.mcfunction
  gm4_metallurgy/data/gm4_musical_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_sensus_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_spiraculum_shamir/loot_tables/band.json
  gm4_metallurgy/data/gm4_tinker_shamir/loot_tables/band.json
  gm4_moneo_shamir/data/gm4_moneo_shamir/loot_tables/band.json
  gm4_percurro_shamir/data/gm4_percurro_shamir/loot_tables/band.json
Labels: fix, needs feedback, needs testing

#440 Move the gm4 tags to the correct place in the fix function
  gm4_heart_canisters/data/gm4_heart_canisters/functions/main.mcfunction
Labels: fix, needs testing

#451 Fix double band creation bug
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/sustain_mould.mcfunction
Labels: fix, needs-testing

#460 Lumos: Added support for netherite tools
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/mark_item_validity.mcfunction
Labels: feature-update

#461 Helious: Added support for netherite armour
  gm4_weighted_armour/data/gm4_helious_shamir/functions/mark_item_validity.mcfunction
Labels: feature-update
