Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2020-11, with the labels that each got.

#429 Add Cozy Campfires (1.16)
  gm4_cozy_campfires/data/gm4_cozy_campfires/advancements/place_campfire.json
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/placement/advance_ray.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/placement/any.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/placement/cast_ray.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/structure/validate.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/init.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/load.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/main.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/player/near_cozy_campfire.mcfunction
  gm4_cozy_campfires/data/load/tags/functions/gm4_cozy_campfires.json
  gm4_cozy_campfires/data/load/tags/functions/load.json
  gm4_cozy_campfires/pack.mcmeta
Labels: module, server-testing

#471 Add Wormhole Tanks and support for Multi-Use Zauber Potions
  gm4_liquid_minecarts/data/gm4_liquid_minecarts/functions/try_to_load.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/init.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/player/wormhole_targeting/read_target_coordinates.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/player/wormhole_targeting/set_dimension.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/init.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_drain.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_drain/zauber_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_drain/zauber_wormhole_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_harming_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_healing_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_leaping_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_poison_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_regeneration_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_strength_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_swiftness_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_wormhole_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/liquid_init/wormhole.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/remove_liquid_tags.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/tank_init.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/util/wormhole.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/util_below.mcfunction
  gm4_zauber_liquids/pack.mcmeta
Labels: feature-update, server-testing

#483 Use predicates for Orbis biome detection
  gm4_orbis/data/gm4_orbis/functions/chunk/get_biomes.mcfunction
  gm4_orbis/data/gm4_orbis/functions/chunk/scan.mcfunction
  gm4_orbis/data/gm4_orbis/loot_tables/detect_biome.json
  gm4_orbis/data/gm4_orbis/predicates/biome/badlands.json
  gm4_orbis/data/gm4_orbis/predicates/biome/beach.json
  gm4_orbis/data/gm4_orbis/predicates/biome/border.json
  gm4_orbis/data/gm4_orbis/predicates/biome/cold.json
  gm4_orbis/data/gm4_orbis/predicates/biome/desert.json
  gm4_orbis/data/gm4_orbis/predicates/biome/forest.json
  gm4_orbis/data/gm4_orbis/predicates/biome/lush.json
  gm4_orbis/data/gm4_orbis/predicates/biome/ocean.json
  gm4_orbis/data/gm4_orbis/predicates/biome/plains.json
  gm4_orbis/data/gm4_orbis/predicates/biome/river.json
  gm4_orbis/data/gm4_orbis/predicates/biome/snowy.json
  gm4_orbis/data/gm4_orbis/predicates/biome/warm.json
  gm4_orbis/data/gm4_orbis/predicates/generate.py
Labels: quality-update
