Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2020-05, with the labels that each got.

#392 Standard Crafting Recipe Polish
  gm4_standard_crafting/data/gm4_standard_crafting/functions/recipe_check.mcfunction
  gm4_standard_crafting/data/gm4_standard_crafting/functions/slabs_recipes.mcfunction
  gm4_standard_crafting/data/gm4_standard_crafting/functions/stairs_recipes.mcfunction
Labels: needs feedback, update

#399 Update Ink Spitting Squid
  gm4_ink_spitting_squid/data/gm4/advancements/ink_spitting_squid.json
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/functions/main.mcfunction
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/functions/squid_squirt.mcfunction
  gm4_ink_spitting_squid/pack.mcmeta
Labels: tested, update

#401 Add slow_falling negation to desire lines
  gm4_desire_lines/data/gm4_desire_lines/functions/player.mcfunction
  gm4_desire_lines/data/gm4_desire_lines/predicates/has_slow_falling.json
Labels: tested, update

#394 Fix End Fishing for 1.15
  gm4_end_fishing/data/gm4/advancements/end_fishing_phantom.json
  gm4_end_fishing/data/gm4/advancements/end_fishing_swords.json
  gm4_end_fishing/data/gm4_end_fishing/advancements/check_inventory.json
  gm4_end_fishing/data/gm4_end_fishing/functions/cast_rod/marker.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/cast_rod/store_data.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/cast_rod/summon_bait.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/durability/check.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/durability/set_mainhand.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/durability/set_offhand.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/enderpuff/apply_levitation.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/enderpuff/apply_slow_falling.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/enderpuff/check_inventory.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/enderpuff/clear_levitation.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/enderpuff/process.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/enderpuff/track_inventory.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/go_fish/bobber_animation.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/go_fish/summon_fish_particle.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/init.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/main.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/lore/armor.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/lore/horse_armor.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/lore/ore.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/lore/sword.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/lore/tool.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/reel_loot.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/set_data.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/set_lore.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/spawn_phantom.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/reel_in/summon_entity.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/set_id.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/loot_tables/gameplay/fish/debris.json
  gm4_end_fishing/data/gm4_end_fishing/loot_tables/gameplay/fish/end_city_treasure.json
  gm4_end_fishing/data/gm4_end_fishing/loot_tables/gameplay/fish/scattered_treasure.json
  gm4_end_fishing/data/gm4_end_fishing/loot_tables/gameplay/fish/valuables.json
  gm4_end_fishing/data/gm4_end_fishing/loot_tables/gameplay/fishing.json
  gm4_end_fishing/pack.mcmeta
Labels: improvement, update

#383 Add Podzol Rooting Soil
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/init.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/load.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/main.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/plant/force.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/plant/normal.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/process_saplings.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/randomizer.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/functions/tag_saplings.mcfunction
  gm4_podzol_rooting_soil/data/gm4_podzol_rooting_soil/tags/blocks/air.json
  gm4_podzol_rooting_soil/data/load/tags/functions/gm4_podzol_rooting_soil.json
  gm4_podzol_rooting_soil/data/load/tags/functions/load.json
  gm4_podzol_rooting_soil/pack.mcmeta
Labels: module, server testing, submission

#409 Add golden hoe to tinker shamir
  gm4_metallurgy/data/gm4_tinker_shamir/functions/mark_item_validity.mcfunction
Labels: fix

#411 Allow Hypexperia on fishing rods
  gm4_metallurgy/data/gm4_hypexperia_shamir/functions/mark_item_validity.mcfunction
Labels: tested

#412 Percurro Shamir
  gm4_percurro_shamir/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_percurro_shamir/data/gm4_metallurgy/tags/functions/summon_band/thorium_brass.json
  gm4_percurro_shamir/data/gm4_percurro_shamir/advancements/use.json
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_item_validity.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_0.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_1.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_2.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_3.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_4.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_n1.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_n2.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/check_teleport_destination/y_n3.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/init.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/load.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/mark_item_validity.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/search_destination.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/summon_band.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/functions/teleport.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/loot_tables/band.json
  gm4_percurro_shamir/data/gm4_percurro_shamir/tags/blocks/valid_destination.json
  gm4_percurro_shamir/data/load/tags/functions/gm4_metallurgy.json
  gm4_percurro_shamir/data/load/tags/functions/gm4_percurro_shamir.json
  gm4_percurro_shamir/data/load/tags/functions/load.json
  gm4_percurro_shamir/pack.mcmeta
Labels: module, tested

#388 Add Chorus Fruit to Falling Stars
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/spawn_falling_star.mcfunction
Labels: suggestion

#398 Added Elytra to Moneo
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/active_armor_chest.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/active_tool.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/armor/elytra.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/main.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/mark_item_validity.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/store_maximum.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/tools/materials/diamond.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/tools/materials/gold.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/tools/materials/iron.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/tools/materials/stone.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/tools/materials/wood.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/functions/tools/shears.mcfunction
  gm4_moneo_shamir/data/gm4_moneo_shamir/predicates/holding_moneo.json
  gm4_moneo_shamir/data/gm4_moneo_shamir/predicates/wear_chest_moneo.json
  gm4_moneo_shamir/data/gm4_moneo_shamir/tags/items/tools.json
Labels: update

#400 Lumos Shamir
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/active.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/check_item_validity.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/init.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/load.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/main.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/mark_item_validity.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/place_torch.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/summon_band.mcfunction
  gm4_lumos_shamir/data/gm4_lumos_shamir/loot_tables/band.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/predicates/check_air.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/predicates/check_block.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/predicates/holding_lumos.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/tags/blocks/air.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/tags/blocks/fence_gates.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/tags/blocks/torch_placeable.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/tags/blocks/torch_unplaceable.json
  gm4_lumos_shamir/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_lumos_shamir/data/gm4_metallurgy/tags/functions/summon_band/thorium_brass.json
  gm4_lumos_shamir/data/load/tags/functions/gm4_lumos_shamir.json
  gm4_lumos_shamir/data/load/tags/functions/gm4_metallurgy.json
  gm4_lumos_shamir/data/load/tags/functions/load.json
  gm4_lumos_shamir/pack.mcmeta
Labels: module, submission
