Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-06, with the labels that each got.

#581 Metallurgy Arborenda: Disable by sneaking
  gm4_metallurgy/data/gm4_metallurgy/predicates/arborenda_active.json
Labels: feature-update, server-testing, tested

#578 Tnt landmines fix
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/recipe_check.mcfunction
Labels: fix

#576 Add lib_lore
  gm4_metallurgy/data/gm4_metallurgy/functions/load.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/add_band/found_item.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/remove_band/check.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/remove_band/clear_data.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/remove_band/finish_item.mcfunction
  gm4_metallurgy/data/load/tags/functions/gm4_lore.json
  gm4_metallurgy/data/load/tags/functions/gm4_metallurgy.json
  gm4_metallurgy/pack.mcmeta
  lib_lore/data/gm4_lore-1.0/functions/algorithms/insert.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/algorithms/remove.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/algorithms/replace.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/algorithms/search.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/enumerate.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/load.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/resolve_algorithm/insert.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/resolve_algorithm/remove.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/resolve_algorithm/replace.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/resolve_algorithm/search.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/resolve_load.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/clean_up.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/find_line.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/insert/insert_after.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/prepare.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/remove/extra_lines.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/remove/remove_rest.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/start_after.mcfunction
  lib_lore/data/gm4_lore-1.0/functions/utilities/start_before.mcfunction
  lib_lore/data/gm4_lore/tags/functions/insert.json
  lib_lore/data/gm4_lore/tags/functions/remove.json
  lib_lore/data/gm4_lore/tags/functions/replace.json
  lib_lore/data/gm4_lore/tags/functions/resolve_algorithm/insert.json
  lib_lore/data/gm4_lore/tags/functions/resolve_algorithm/remove.json
  lib_lore/data/gm4_lore/tags/functions/resolve_algorithm/replace.json
  lib_lore/data/gm4_lore/tags/functions/resolve_algorithm/search.json
  lib_lore/data/gm4_lore/tags/functions/search.json
  lib_lore/data/load/tags/functions/gm4_lore.json
  lib_lore/data/load/tags/functions/gm4_lore/enumerate.json
  lib_lore/data/load/tags/functions/gm4_lore/resolve_load.json
  lib_lore/pack.mcmeta
  lib_lore/pack.png
Labels: quality-update, server-testing

#595 Add Vecto Shamir (temporary boat/minecart)
  gm4_vecto_shamir/data/gm4/tags/items/boots.json
  gm4_vecto_shamir/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_vecto_shamir/data/gm4_metallurgy/tags/functions/summon_band/copper.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/advancements/join.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/advancements/vehicle_check.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/active.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/check_item_validity.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/get_id.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/init.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/load.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/main.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/mark_item_validity.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/summon_band.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/check.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/check_boat_collision.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/position_check.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/remove.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/spawn_boat.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/spawn_minecart.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/loot_tables/band.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/biome/acacia.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/biome/birch.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/biome/dark_oak.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/biome/jungle.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/biome/spruce.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/in_vehicle.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/sneak_validblock.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/sneaking.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/predicates/water.json
  gm4_vecto_shamir/data/gm4_vecto_shamir/tags/entity_types/vehicle.json
  gm4_vecto_shamir/data/load/tags/functions/gm4_metallurgy.json
  gm4_vecto_shamir/data/load/tags/functions/gm4_vecto_shamir.json
  gm4_vecto_shamir/data/load/tags/functions/load.json
  gm4_vecto_shamir/pack.mcmeta
Labels: module, server-testing, submission

#596 Add Iacio Shamir (throw further)
  gm4_iacio_shamir/data/gm4_iacio_shamir/advancements/inventory_changed.json
  gm4_iacio_shamir/data/gm4_iacio_shamir/functions/add_motion.mcfunction
  gm4_iacio_shamir/data/gm4_iacio_shamir/functions/check_item_validity.mcfunction
  gm4_iacio_shamir/data/gm4_iacio_shamir/functions/check_throw.mcfunction
  gm4_iacio_shamir/data/gm4_iacio_shamir/functions/init.mcfunction
  gm4_iacio_shamir/data/gm4_iacio_shamir/functions/load.mcfunction
  gm4_iacio_shamir/data/gm4_iacio_shamir/functions/mark_item_validity.mcfunction
  gm4_iacio_shamir/data/gm4_iacio_shamir/functions/summon_band.mcfunction
  gm4_iacio_shamir/data/gm4_iacio_shamir/loot_tables/band.json
  gm4_iacio_shamir/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_iacio_shamir/data/gm4_metallurgy/tags/functions/summon_band/barium.json
  gm4_iacio_shamir/data/load/tags/functions/gm4_iacio_shamir.json
  gm4_iacio_shamir/data/load/tags/functions/gm4_metallurgy.json
  gm4_iacio_shamir/data/load/tags/functions/load.json
  gm4_iacio_shamir/pack.mcmeta
Labels: module, server-testing, submission

#611 Add Undead Horses to Everstone
  gm4_everstone/data/gm4_everstone/tags/entity_types/affected.json
Labels: feature-update

#597 Poses Pack advancement renamed
  gm4_poses_pack/data/gm4/advancements/poses_pack.json
  gm4_poses_pack/data/gm4_poses_pack/functions/pose_changed.mcfunction
Labels: quality-update

#594 Added Audere Shamir
  gm4_audere_shamir/data/gm4_audere_shamir/functions/active_tool.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/check_item_validity.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/init.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/load.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/main.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/mark_item_validity.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/store_maximum.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/summon_band.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/tools/materials/diamond.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/tools/materials/gold.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/tools/materials/iron.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/tools/materials/netherite.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/tools/materials/stone.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/tools/materials/wood.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/tools/shears.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/functions/update_netherite.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/loot_tables/band.json
  gm4_audere_shamir/data/gm4_audere_shamir/predicates/holding_audere.json
  gm4_audere_shamir/data/gm4_audere_shamir/predicates/holding_netherite.json
  gm4_audere_shamir/data/gm4_audere_shamir/tags/items/netherite_tools.json
  gm4_audere_shamir/data/gm4_audere_shamir/tags/items/tools.json
  gm4_audere_shamir/data/gm4_metallurgy/tags/functions/apply_band.json
  gm4_audere_shamir/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_audere_shamir/data/gm4_metallurgy/tags/functions/summon_band/barium.json
  gm4_audere_shamir/data/load/tags/functions/gm4_audere_shamir.json
  gm4_audere_shamir/data/load/tags/functions/gm4_metallurgy.json
  gm4_audere_shamir/data/load/tags/functions/load.json
  gm4_audere_shamir/pack.mcmeta
  gm4_audere_shamir/pack.png
Labels: module, server-testing, submission
