Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-11, with the labels that each got.

#686 Implement improved Falling Star spawning algorithm
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/event.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/falling_star/accumulate_impact_points.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/falling_star/decay.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/falling_star/initilize.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/falling_star/select_spawn_location.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/falling_star/spawn.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/falling_star/start_in_area.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/find_location.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/spawn_falling_star.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/star_shower.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/predicates/shower_chance.json
  gm4_mysterious_midnights/data/gm4_falling_stars/predicates/spawn_chance.json
  gm4_mysterious_midnights/data/gm4_falling_stars/tags/entity_types/falling_star.json
  gm4_mysterious_midnights/data/gm4_mysterious_midnights/functions/init.mcfunction
Labels: module, needs-testing, quality-update

#691 Vecto Shamir: Small improvement to vehicle check
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/active.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/check_item_validity.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/get_id.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/mark_item_validity.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/summon_band.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/check.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/check_boat_collision.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/position_check.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/remove.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/spawn_boat.mcfunction
  gm4_vecto_shamir/data/gm4_vecto_shamir/functions/vehicle/spawn_minecart.mcfunction
Labels: needs-testing, quality-update, server-testing

#690 Chairs: General update for smaller issues
  gm4_chairs/data/gm4_chairs/advancements/sitting_in_chair.json
  gm4_chairs/data/gm4_chairs/functions/create_chair.mcfunction
  gm4_chairs/data/gm4_chairs/functions/hit.mcfunction
  gm4_chairs/data/gm4_chairs/functions/init.mcfunction
  gm4_chairs/data/gm4_chairs/functions/kill.mcfunction
  gm4_chairs/data/gm4_chairs/functions/lightning/delay.mcfunction
  gm4_chairs/data/gm4_chairs/functions/lightning/revive_chair.mcfunction
  gm4_chairs/data/gm4_chairs/functions/lightning/tag.mcfunction
  gm4_chairs/data/gm4_chairs/functions/main.mcfunction
  gm4_chairs/data/gm4_chairs/functions/sit/check.mcfunction
  gm4_chairs/data/gm4_chairs/functions/sit/counter.mcfunction
  gm4_chairs/data/gm4_chairs/functions/sit_counter.mcfunction
  gm4_chairs/data/gm4_chairs/loot_tables/drop_saddle.json
  gm4_chairs/data/gm4_chairs/predicates/sitting_in_chair.json
Labels: tested, quality-update

#692 Crossbow Cartridges: Tripwire hook endpoint
  gm4_crossbow_cartridges/data/gm4/advancements/crossbow_cartridges_string.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/place_hook.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/shoot_arrow.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/cables/unspool_string.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/init.mcfunction
Labels: tested, feature-update

#693 Apple Trees: Pick apples while holding any item
  gm4_apple_trees/data/gm4_apple_trees/advancements/apple_hand_empty.json
  gm4_apple_trees/data/gm4_apple_trees/advancements/apple_hand_item.json
  gm4_apple_trees/data/gm4_apple_trees/functions/apple/hand_interact.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/apple/interact.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/apple/pick.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/generate.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/initialize.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/set_stage/0.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/set_stage/1.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/set_stage/2.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/item_modifiers/count.json
  gm4_apple_trees/data/gm4_apple_trees/predicates/apple_holding.json
  gm4_apple_trees/data/gm4_apple_trees/predicates/apple_picked.json
Labels: tested, feature-update

#696 Add lib_potion_tracking
  gm4_display_frames/data/gm4_display_frames/functions/init.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/load.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/potion_tracking/splash_item_frames.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/potion_tracking/tag_potion.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/potion_tracking/verify_landed_potion.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/check_splash.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/kill.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/spawn_tracker.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/tick.mcfunction
  gm4_display_frames/data/gm4_display_frames/predicates/invisibility_potion.json
  gm4_display_frames/data/gm4_potion_tracking/tags/functions/potion_landed.json
  gm4_display_frames/data/gm4_potion_tracking/tags/functions/tag_potion.json
  gm4_display_frames/data/load/tags/functions/gm4_display_frames.json
  gm4_display_frames/pack.mcmeta
  lib_forceload/data/gm4_forceload-1.0/functions/init_chunk.mcfunction
  lib_forceload/data/gm4_forceload-1.0/functions/init_ow_chunk.mcfunction
  lib_forceload/data/gm4_forceload-1.0/functions/load.mcfunction
  lib_forceload/data/gm4_forceload/tags/functions/command_block_tick.json
  lib_potion_tracking/README.md
  lib_potion_tracking/data/gm4/tags/functions/command_block_tick.json
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/enumerate.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/load.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/potion.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/resolve_load.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/resolve_tick.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/tick.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/track/check_marker.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/track/check_potion.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/track/initialize_potion.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/track/marker.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/track/potion.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking-1.0/functions/track/potion_landed.mcfunction
  lib_potion_tracking/data/gm4_potion_tracking/tags/functions/potion_landed.json
  lib_potion_tracking/data/gm4_potion_tracking/tags/functions/tag_potion.json
  lib_potion_tracking/data/load/tags/functions/gm4_potion_tracking.json
  lib_potion_tracking/data/load/tags/functions/gm4_potion_tracking/dependencies.json
  lib_potion_tracking/data/load/tags/functions/gm4_potion_tracking/enumerate.json
  lib_potion_tracking/data/load/tags/functions/gm4_potion_tracking/resolve_load.json
  lib_potion_tracking/pack.mcmeta
  lib_potion_tracking/pack.png
Labels: submission

#677 Add lib_brewing
  gm4_potion_liquids/data/gm4_brewing/tags/functions/insert/lingering.json
  gm4_potion_liquids/data/gm4_brewing/tags/functions/insert/splash.json
  gm4_potion_liquids/data/gm4_potion_liquids/functions/brewing_stand/lingering.mcfunction
  gm4_potion_liquids/data/gm4_potion_liquids/functions/brewing_stand/splash.mcfunction
  gm4_potion_liquids/data/gm4_potion_liquids/functions/load.mcfunction
  gm4_potion_liquids/data/gm4_potion_liquids/loot_tables/lingering_floating_potion.json
  gm4_potion_liquids/data/gm4_potion_liquids/loot_tables/splash_floating_potion.json
  gm4_potion_liquids/data/gm4_potion_liquids/loot_tables/technical/brewing_stand/lingering.json
  gm4_potion_liquids/data/gm4_potion_liquids/loot_tables/technical/brewing_stand/splash.json
  gm4_potion_liquids/data/load/tags/functions/gm4_potion_liquids.json
  gm4_potion_liquids/pack.mcmeta
  gm4_zauber_cauldrons/data/gm4_brewing/tags/functions/insert/lingering.json
  gm4_zauber_cauldrons/data/gm4_brewing/tags/functions/insert/splash.json
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/brewing_stand/lingering.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/brewing_stand/splash.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/load.mcfunction
  gm4_zauber_cauldrons/data/load/tags/functions/gm4_zauber_cauldrons.json
  gm4_zauber_cauldrons/pack.mcmeta
  lib_brewing/README.md
  lib_brewing/data/gm4_brewing-1.0/advancements/place_brewing_stand.json
  lib_brewing/data/gm4_brewing-1.0/functions/check_brew.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/enumerate.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/get_brewing_stand.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/lingering/check_items.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/lingering/slot_0.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/lingering/slot_1.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/lingering/slot_2.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/splash/check_items.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/splash/slot_0.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/splash/slot_1.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finalize_potions/splash/slot_2.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/finish_brew.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/load.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/main.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/place_brewing_stand.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/prep_finish_brew.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/process.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/ray.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/ray_backup.mcfunction
  lib_brewing/data/gm4_brewing-1.0/functions/resolve_load.mcfunction
  lib_brewing/data/gm4_brewing/tags/functions/finish_brew.json
  lib_brewing/data/gm4_brewing/tags/functions/insert/lingering.json
  lib_brewing/data/gm4_brewing/tags/functions/insert/splash.json
  lib_brewing/data/load/tags/functions/gm4_brewing.json
  lib_brewing/data/load/tags/functions/gm4_brewing/enumerate.json
  lib_brewing/data/load/tags/functions/gm4_brewing/resolve_load.json
  lib_brewing/pack.mcmeta
  lib_brewing/pack.png
Labels: submission

#698 Adds Lightning in a Bottle
  gm4_lightning_in_a_bottle/data/gm4/advancements/lightning_in_a_bottle_drink.json
  gm4_lightning_in_a_bottle/data/gm4/advancements/lightning_in_a_bottle_shulker.json
  gm4_lightning_in_a_bottle/data/gm4/advancements/root.json
  gm4_lightning_in_a_bottle/data/gm4_brewing/tags/functions/insert/lingering.json
  gm4_lightning_in_a_bottle/data/gm4_brewing/tags/functions/insert/splash.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/advancements/drink_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/advancements/lightning_strike.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/brew/lingering.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/brew/splash.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/check_fuel.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/check_potions.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/consume_fuel.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/lingering/slot_0.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/lingering/slot_1.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/lingering/slot_2.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/slot_0.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/slot_1.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/slot_2.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/splash/slot_0.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/splash/slot_1.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/splash/slot_2.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/entity/evoker.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/entity/guardian.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/entity/illusioner.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/entity/shulker.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/init.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/lightning/check.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/lightning/locate.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/lightning/spawner_check.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/lightning/strike_self.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/load.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/main.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/potion_tracking/modify_cloud.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/potion_tracking/potion_landed.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/potion_tracking/tag_potion.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/potion_tracking/verify_landed_potion.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/item_modifiers/set_zero.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/entities/charged_creeper.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/entities/illusioner.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/entities/shulker.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/lingering_bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/lingering_potion_of_blindness.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/splash_bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/lingering/bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/splash/bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/predicates/random_strike.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/tags/entity_types/potion_tracker.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/tags/functions/lightning_strike.json
  gm4_lightning_in_a_bottle/data/gm4_potion_tracking/tags/functions/potion_landed.json
  gm4_lightning_in_a_bottle/data/gm4_potion_tracking/tags/functions/tag_potion.json
  gm4_lightning_in_a_bottle/data/gm4_spawner_minecarts/tags/functions/spawner_check.json
  gm4_lightning_in_a_bottle/data/load/tags/functions/gm4_lightning_in_a_bottle.json
  gm4_lightning_in_a_bottle/data/load/tags/functions/load.json
  gm4_lightning_in_a_bottle/pack.mcmeta
Labels: module, submission

#703 Update LiaB for more consistant lightning rod activation & LiaB Creation
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/lightning/check.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/main.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/potion_tracking/potion_landed.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/sustain_lingering_lightning.mcfunction
Labels: tested

#704 Missing lib brewing nbt update
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/lingering/bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/splash/bottle_of_lightning.json
Labels: fix

#705 Add connected texture to Lightning in a Bottle brewing stand when a lightning rod is placed on top
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/advancements/place_lightning_rod.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/texture_connector/check_structure.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/texture_connector/force_update.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/texture_connector/process.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/init.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/load.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/main.mcfunction
Labels: quality-update
