Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-05, with the labels that each got.

#418 Add Washing Tanks
  gm4_washing_tanks/data/gm4_liquid_tanks/tags/functions/item_fill.json
  gm4_washing_tanks/data/gm4_washing_tanks/functions/init.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/item_fill.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/load.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/wash.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/armour.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/bed.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/book.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/carpet.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/glass.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/glass_pane.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/map.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/shulker_box.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/terracotta.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/functions/washing_recipes/wool.mcfunction
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/armour.json
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/bed.json
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/carpet.json
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/glass.json
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/glass_pane.json
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/shulker_box.json
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/terracotta.json
  gm4_washing_tanks/data/gm4_washing_tanks/predicates/wool.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/armour.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/bed.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/carpet.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/glass.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/glass_pane.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/shulker_box.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/terracotta.json
  gm4_washing_tanks/data/gm4_washing_tanks/tags/items/wool.json
  gm4_washing_tanks/data/load/tags/functions/gm4_liquid_tanks.json
  gm4_washing_tanks/data/load/tags/functions/gm4_washing_tanks.json
  gm4_washing_tanks/data/load/tags/functions/load.json
  gm4_washing_tanks/pack.mcmeta
Labels: module, submission, tested

#566 Make Zauber Armour keep existing CMD
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/knockback_resistance.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/speed_boost.mcfunction
Labels: fix

#590 Make lib_player_heads actually work
  gm4_end_fishing/data/gm4_end_fishing/functions/load.mcfunction
  gm4_end_fishing/data/load/tags/functions/gm4_player_heads.json
  gm4_end_fishing/pack.mcmeta
  gm4_heart_canisters/data/gm4_heart_canisters/functions/load.mcfunction
  gm4_heart_canisters/data/load/tags/functions/gm4_player_heads.json
  gm4_heart_canisters/pack.mcmeta
Labels: fix

#598 Prevents spectators from making armor stands glow
  gm4_better_armour_stands/data/gm4_better_armour_stands/functions/main.mcfunction
Labels: fix

#600 Optimize Tinker
  gm4_metallurgy/data/gm4_tinker_shamir/functions/active.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/hoe.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/pickaxe.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/shovel.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/sword.mcfunction
Labels: needs-testing, quality-update
