Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-12, with the labels that each got.

#720 Chairs: Remove pig health display
  gm4_chairs/data/gm4_chairs/functions/create_chair.mcfunction
  gm4_chairs/data/gm4_chairs/functions/kill.mcfunction
Labels: fix

#718 Vibro Multiplayer Fix
  gm4_metallurgy/data/gm4_vibro_shamir/functions/shock/activate.mcfunction
Labels: fix, server-testing

#719 Ink Spitting Squid Disabled by Conduit Power
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/functions/main.mcfunction
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/predicates/in_water.json
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/predicates/inkable.json
Labels: tested, feature-update, server-testing
