Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-04, with the labels that each got.

#547 Updated Heart Cans' skull textures
  gm4_heart_canisters/data/gm4/advancements/heart_canisters_max.json
  gm4_heart_canisters/data/gm4/advancements/heart_canisters_tier_1.json
  gm4_heart_canisters/data/gm4/advancements/heart_canisters_tier_2.json
  gm4_heart_canisters/data/gm4_heart_canisters/functions/main.mcfunction
  gm4_heart_canisters/data/gm4_heart_canisters/functions/recipe_check.mcfunction
Labels: feature-update

#548 Update Enderpuff texture
  gm4_end_fishing/data/gm4_end_fishing/functions/main.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/loot_tables/gameplay/fish/enderpuff.json
Labels: feature-update

#551 Include lib_player_heads to increase efficiency and maintainability of custom player heads
  gm4_end_fishing/data/gm4_end_fishing/functions/init.mcfunction
  gm4_end_fishing/data/gm4_end_fishing/functions/main.mcfunction
  gm4_end_fishing/data/load/tags/functions/gm4_end_fishing.json
  gm4_heart_canisters/data/gm4_heart_canisters/functions/init.mcfunction
  gm4_heart_canisters/data/gm4_heart_canisters/functions/main.mcfunction
  gm4_heart_canisters/data/load/tags/functions/gm4_heart_canisters.json
  lib_player_heads/data/gm4_player_heads-1.0/functions/enumerate.mcfunction
  lib_player_heads/data/gm4_player_heads-1.0/functions/load.mcfunction
  lib_player_heads/data/gm4_player_heads-1.0/functions/main.mcfunction
  lib_player_heads/data/gm4_player_heads-1.0/functions/repair.mcfunction
  lib_player_heads/data/gm4_player_heads-1.0/functions/repair_continue.mcfunction
  lib_player_heads/data/gm4_player_heads-1.0/functions/repair_loop.mcfunction
  lib_player_heads/data/gm4_player_heads-1.0/functions/resolve_load.mcfunction
  lib_player_heads/data/load/tags/functions/gm4_player_heads.json
  lib_player_heads/data/load/tags/functions/gm4_player_heads/enumerate.json
  lib_player_heads/data/load/tags/functions/gm4_player_heads/resolve_load.json
  lib_player_heads/pack.mcmeta
  lib_player_heads/pack.png
Labels: quality-update

#550 Include lib_trades to make Wandering Trader recipes available to more modules
  gm4_apple_trees/data/gm4_apple_trees/functions/wandering_trader/register_trade.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/main.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/wandering_trader/add_trade.mcfunction
  gm4_apple_trees/data/gm4_trades/tags/functions/register_trades.json
  gm4_apple_trees/data/load/tags/functions/gm4_fruiting_trees.json
  gm4_apple_trees/pack.mcmeta
  lib_trades/data/gm4_trades-1.0/functions/enumerate.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/load.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/main.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/resolve_load.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/wandering_trader/append_trade.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/wandering_trader/create_pool.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/wandering_trader/modify.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/wandering_trader/pool/collect_trades.mcfunction
  lib_trades/data/gm4_trades-1.0/functions/wandering_trader/pool/initialize.mcfunction
  lib_trades/data/gm4_trades/tags/functions/register_trades.json
  lib_trades/data/load/tags/functions/gm4_trades.json
  lib_trades/data/load/tags/functions/gm4_trades/enumerate.json
  lib_trades/data/load/tags/functions/gm4_trades/resolve_load.json
  lib_trades/pack.mcmeta
  lib_trades/pack.png
Labels: quality-update

#557 Tunnel Bores should not break liquids
  gm4_tunnel_bores/data/gm4_tunnel_bores/tags/blocks/unbreakable.json
Labels: fix

#482 Updated Tinker shamir and Tinkering Compressors
  gm4_metallurgy/data/gm4_tinker_shamir/functions/active.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/slime_ball.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/compact/sword.mcfunction
  gm4_metallurgy/data/gm4_tinker_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/pack.mcmeta
  gm4_tinkering_compressors/data/gm4_tinkering_compressors/functions/compress/netherite_ingot.mcfunction
  gm4_tinkering_compressors/data/gm4_tinkering_compressors/functions/compress/slime_ball.mcfunction
  gm4_tinkering_compressors/data/gm4_tinkering_compressors/functions/decompress/netherite_block.mcfunction
  gm4_tinkering_compressors/data/gm4_tinkering_compressors/functions/decompress/slime_block.mcfunction
  gm4_tinkering_compressors/data/gm4_tinkering_compressors/functions/mode/compress.mcfunction
  gm4_tinkering_compressors/data/gm4_tinkering_compressors/functions/mode/decompress.mcfunction
  gm4_tinkering_compressors/pack.mcmeta
Labels: feature-update, tested

#521 Poses pack: add paste and move
  gm4_poses_pack/data/gm4_poses_pack/functions/apply_book.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/copy.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/init.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/paste.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/arms.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/body.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/head.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/legs.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/arm_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/arm_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/body.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/flip_body.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/head.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/leg_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/leg_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/update_values.mcfunction
Labels: feature-update, tested

#545 Give Brewer and Congealed Enchantments' name a section symbol at the end
  gm4_enchantment_extractors/data/gm4_enchantment_extractors/functions/extract_failed.mcfunction
  gm4_mob_conversion/data/gm4_mob_conversion/functions/convert_witch.mcfunction
Labels: feature-update

#539 Better Armour Stands: Add head/hand interaction
  gm4_better_armour_stands/data/gm4_better_armour_stands/functions/apply_book.mcfunction
  gm4_better_armour_stands/data/gm4_better_armour_stands/functions/equip/hand.mcfunction
  gm4_better_armour_stands/data/gm4_better_armour_stands/functions/equip/head.mcfunction
  gm4_better_armour_stands/data/gm4_better_armour_stands/functions/equip/offhand.mcfunction
Labels: feature-update, tested

#518 Speed Paths' speed boost: potion effect -> attribute modifier
  gm4_speed_paths/data/gm4_speed_paths/functions/apply_effects/add_speed.mcfunction
  gm4_speed_paths/data/gm4_speed_paths/functions/apply_effects/check_path.mcfunction
  gm4_speed_paths/data/gm4_speed_paths/functions/apply_effects/remove_speed.mcfunction
  gm4_speed_paths/data/gm4_speed_paths/functions/init.mcfunction
  gm4_speed_paths/data/gm4_speed_paths/functions/main.mcfunction
  gm4_speed_paths/pack.mcmeta
Labels: quality-update, tested

#560 Make Metallurgy emulate vanilla anvil behavior
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/set_mould.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/add_band/found_item.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/anvil/degrade.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/anvil/degrade/anvil.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/anvil/degrade/chipped_anvil.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/anvil/degrade/damaged_anvil.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/anvil/use.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/smooshing/remove_band/found_obsidian.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/predicates/smooshing/anvil_damage_chance.json
Labels: feature-update, server-testing

#569 Display Frames - Kill Lazy Loaded AECs
  gm4_display_frames/data/gm4_display_frames/functions/init.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/main.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/kill.mcfunction
Labels: quality-update, tested

#564 Desire Lines: Add Celaro Shamir
  gm4_desire_lines/data/gm4/tags/items/boots.json
  gm4_desire_lines/data/gm4_celaro_shamir/functions/active.mcfunction
  gm4_desire_lines/data/gm4_celaro_shamir/functions/check_item_validity.mcfunction
  gm4_desire_lines/data/gm4_celaro_shamir/functions/mark_item_validity.mcfunction
  gm4_desire_lines/data/gm4_celaro_shamir/functions/summon_band.mcfunction
  gm4_desire_lines/data/gm4_celaro_shamir/functions/tick.mcfunction
  gm4_desire_lines/data/gm4_celaro_shamir/loot_tables/band.json
  gm4_desire_lines/data/gm4_celaro_shamir/predicates/shamir_active.json
  gm4_desire_lines/data/gm4_celaro_shamir/tags/blocks/tall_plants.json
  gm4_desire_lines/data/gm4_desire_lines/tags/functions/expansion.json
  gm4_desire_lines/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_desire_lines/data/gm4_metallurgy/tags/functions/summon_band/aluminium.json
Labels: feature-update, server-testing, tested

#563 Revise boots of ostara functionality
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/active.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/create_boots.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/main.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/plant.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/plant/beetroot.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/plant/carrot.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/plant/nether_wart.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/plant/potato.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/plant/wheat.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/recipe_check.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/armor_stand_grass.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/boots_equipped.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/equipped_with_grass.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/holding_beetroot.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/holding_carrot.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/holding_nether_wart.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/holding_potato.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/holding_seeds.json
Labels: feature-update, server-testing, tested

#572 Activate Celaro Shamir stealth on sneak only
  gm4_desire_lines/data/gm4_celaro_shamir/functions/active.mcfunction
  gm4_desire_lines/data/gm4_celaro_shamir/predicates/stealth_active.json
Labels: tested

#500 Tunnel bores model cosmetics
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/create.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/clear_rotation.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_direction.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_rotation.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_rotation_east.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_rotation_north.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_rotation_south.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/direction/update_rotation_west.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/mine/stop_cart.mcfunction
Labels: feature-update, server-testing, tested
