Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-02, with the labels that each got.

#515 Health Boost potion effect -> Attribute modifiers
  gm4_heart_canisters/data/gm4_heart_canisters/functions/apply_health_boost.mcfunction
  gm4_heart_canisters/data/gm4_heart_canisters/functions/check_heart_canisters.mcfunction
Labels: quality-update, tested

#448 TNT Landmines Fixes
  gm4_tnt_landmines/data/gm4/advancements/tnt_landmines.json
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/blowup/explosive.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/blowup/safe.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/blowup/type_check.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/checks/blowup.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/checks/creation.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/checks/landmine.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/checks/recipe.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/fix_skull.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/init.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/items/create.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/items/disarming.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/items/upgrade.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/main.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/recipe_check.mcfunction
  gm4_tnt_landmines/data/gm4_tnt_landmines/functions/tick.mcfunction
  gm4_tnt_landmines/data/load/tags/functions/gm4_tnt_landmines.json
  gm4_tnt_landmines/pack.mcmeta
Labels: fix, needs-testing, quality-update

#519 Health Boost Effect Compatibility
  gm4_heart_canisters/data/gm4_heart_canisters/functions/apply_health_boost.mcfunction
  gm4_heart_canisters/data/gm4_heart_canisters/predicates/has_health_boost.json
Labels: fix

#514 Repair Relocated Blocks
  gm4_relocators/data/gm4_relocators/functions/place_down/find_head.mcfunction
  gm4_relocators/data/gm4_relocators/functions/place_down/repair.mcfunction
  gm4_relocators/data/gm4_relocators/functions/place_down/replace_head.mcfunction
  gm4_relocators/data/gm4_relocators/functions/place_down/update_command_block.mcfunction
Labels: fix, quality-update, server-testing

#498 Add Everstone
  gm4_everstone/data/gm4/advancements/everstone.json
  gm4_everstone/data/gm4/advancements/root.json
  gm4_everstone/data/gm4_everstone/advancements/kill_age_locked.json
  gm4_everstone/data/gm4_everstone/functions/aging.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/age_mob.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/check_mob.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/guardian.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/piglin.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/skeleton.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/slime.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/stray.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/vindicator.mcfunction
  gm4_everstone/data/gm4_everstone/functions/aging/zombie.mcfunction
  gm4_everstone/data/gm4_everstone/functions/check.mcfunction
  gm4_everstone/data/gm4_everstone/functions/convert/elder_guardian.mcfunction
  gm4_everstone/data/gm4_everstone/functions/convert/evoker.mcfunction
  gm4_everstone/data/gm4_everstone/functions/convert/husk.mcfunction
  gm4_everstone/data/gm4_everstone/functions/convert/magma_cube.mcfunction
  gm4_everstone/data/gm4_everstone/functions/convert/piglin_brute.mcfunction
  gm4_everstone/data/gm4_everstone/functions/convert/skeleton.mcfunction
  gm4_everstone/data/gm4_everstone/functions/convert/stray.mcfunction
  gm4_everstone/data/gm4_everstone/functions/init.mcfunction
  gm4_everstone/data/gm4_everstone/functions/killed_age_locked.mcfunction
  gm4_everstone/data/gm4_everstone/functions/load.mcfunction
  gm4_everstone/data/gm4_everstone/functions/lock_age.mcfunction
  gm4_everstone/data/gm4_everstone/functions/main.mcfunction
  gm4_everstone/data/gm4_everstone/functions/tick.mcfunction
  gm4_everstone/data/gm4_everstone/loot_tables/drop_chance.json
  gm4_everstone/data/gm4_everstone/loot_tables/everstone.json
  gm4_everstone/data/gm4_everstone/predicates/in_bastion_remnant.json
  gm4_everstone/data/gm4_everstone/predicates/in_dry_sunlight.json
  gm4_everstone/data/gm4_everstone/predicates/in_frozen.json
  gm4_everstone/data/gm4_everstone/predicates/in_frozen_sunlight.json
  gm4_everstone/data/gm4_everstone/predicates/in_nether.json
  gm4_everstone/data/gm4_everstone/predicates/is_full_moon.json
  gm4_everstone/data/gm4_everstone/tags/blocks/air.json
  gm4_everstone/data/gm4_everstone/tags/blocks/contains_magic.json
  gm4_everstone/data/gm4_everstone/tags/entity_types/affected.json
  gm4_everstone/data/gm4_everstone/tags/entity_types/aging_mob.json
  gm4_everstone/data/load/tags/functions/gm4_everstone.json
  gm4_everstone/data/load/tags/functions/load.json
  gm4_everstone/pack.mcmeta
Labels: module, server-testing, submission

#447 Add Display Frames
  gm4_display_frames/data/gm4/advancements/display_frames.json
  gm4_display_frames/data/gm4/advancements/root.json
  gm4_display_frames/data/gm4_display_frames/functions/frame/invisible/apply_invisibility.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/frame/invisible/clear_invisibility.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/frame/invisible/create.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/frame/invisible/process.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/init.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/load.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/main.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/check_splash.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/spawn_tracker.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/tick.mcfunction
  gm4_display_frames/data/gm4_display_frames/predicates/invisibility_potion.json
  gm4_display_frames/data/gm4_display_frames/tags/entity_types/frame.json
  gm4_display_frames/data/gm4_display_frames/tags/entity_types/potion_tracker.json
  gm4_display_frames/data/load/tags/functions/gm4_display_frames.json
  gm4_display_frames/data/load/tags/functions/load.json
  gm4_display_frames/pack.mcmeta
  gm4_display_frames/pack.png
Labels: module, server-testing, submission
