Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-07, with the labels that each got.

#618 Added undead ignore tag
  gm4_undead_players/data/gm4_undead_players/functions/died.mcfunction
Labels: fix

#591 Poses Pack: Improve reliability of pose modification
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/arm_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/arm_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/body.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/head.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/leg_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/leg_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_arm_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_arm_right.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_leg_left.mcfunction
  gm4_poses_pack/data/gm4_poses_pack/functions/pose/player/mirror_leg_right.mcfunction
Labels: quality-update

#614 Chairs update 1.17
  gm4_chairs/data/gm4_chairs/advancements/hit.json
  gm4_chairs/data/gm4_chairs/advancements/sitting_in_chair.json
  gm4_chairs/data/gm4_chairs/functions/correction.mcfunction
  gm4_chairs/data/gm4_chairs/functions/create_chair.mcfunction
  gm4_chairs/data/gm4_chairs/functions/hit.mcfunction
  gm4_chairs/data/gm4_chairs/functions/kill.mcfunction
  gm4_chairs/data/gm4_chairs/functions/main.mcfunction
  gm4_chairs/data/gm4_chairs/functions/saddle.mcfunction
  gm4_chairs/data/gm4_chairs/functions/sit_counter.mcfunction
  gm4_chairs/data/gm4_chairs/loot_tables/drop_saddle.json
Labels: feature-update, needs-testing, quality-update

#603 Mysterious Midnights only in Overworld
  gm4_midnight_menaces/data/gm4_enlarging_phantoms/functions/set_pos.mcfunction
  gm4_midnight_menaces/data/gm4_enlarging_phantoms/functions/slow_clock.mcfunction
  gm4_midnight_menaces/data/gm4_icy_strays/functions/event.mcfunction
  gm4_midnight_menaces/data/gm4_illusioner_nights/functions/set_pos.mcfunction
  gm4_midnight_menaces/data/gm4_illusioner_nights/functions/slow_clock.mcfunction
  gm4_midnight_menaces/data/gm4_menacing_goblins/functions/initialise.mcfunction
  gm4_midnight_menaces/data/gm4_menacing_goblins/functions/set_pos.mcfunction
  gm4_midnight_menaces/data/gm4_menacing_goblins/functions/slow_clock.mcfunction
  gm4_midnight_menaces/data/gm4_sandy_husks/functions/event.mcfunction
  gm4_midnight_menaces/data/gm4_slime_fests/functions/event.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/event.mcfunction
  gm4_mysterious_midnights/data/gm4_falling_stars/functions/find_location.mcfunction
  gm4_mysterious_midnights/data/gm4_mysterious_midnights/functions/calculate_difficulty.mcfunction
  gm4_mysterious_midnights/data/gm4_resurrecting_skeletons/functions/event.mcfunction
  gm4_mysterious_midnights/data/gm4_resurrecting_zombies/functions/event.mcfunction
  gm4_mysterious_midnights/data/gm4_tipped_skeletons/functions/event.mcfunction
Labels: fix, needs-testing

#606 Protection 0 and HideFlags
  gm4_everstone/data/gm4_everstone/loot_tables/everstone.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/functions/soul_forge/entities/fire_sprite.mcfunction
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/functions/soul_forge/outputs/create_shard.mcfunction
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/aggressive.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/agile.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/anchoring.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/bargaining.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/bashing.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/blasting.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/blinding.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/bounding.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/bubbly.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/conjuring.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/depriving.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/draining.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/enduring.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/expeditious.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/feathery.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/freezing.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/gazing.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/gliding.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/hawkeye.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/incombustible.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/lifeless.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/neutralizing.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/phasing.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/pricking.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/retreating.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/rushing.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/scaling.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/soaring.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/striding.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/synergetic.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/vanishing.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/venomous.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/volatile.json
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/withering.json
  gm4_soul_glass/data/gm4_soul_glass/functions/destroy.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/modify_output.mcfunction
Labels: fix, quality-update

#620 Added Glow Squid to Ink Spitting Squid
  gm4_ink_spitting_squid/data/gm4/advancements/glow_ink_spitting_squid.json
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/functions/glow_squid_squirt.mcfunction
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/functions/main.mcfunction
  gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/predicates/in_water.json
Labels: feature-update, needs-testing, tested

#632 Re-Add Damage Sound for Sweethearts
  gm4_sweethearts/data/gm4_sweethearts/functions/transfer_donor.mcfunction
Labels: fix

#621 Adds coarse and rooted dirt to BoO grass-able
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/main.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/tags/blocks/dirt.json
Labels: feature-update

#642 Beehive Inspectors: Fix visual bug
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/inspect.mcfunction
Labels: fix
