Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2021-08, with the labels that each got.

#624 Cozy campfires 1.17 update
  gm4_cozy_campfires/data/gm4_cozy_campfires/advancements/place_campfire.json
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/placement/advance_ray.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/placement/any.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/placement/cast_ray.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/campfire/structure/validate.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/cozy_campfire.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/cozy_player.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/init.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/main.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/placement/place.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/placement/ray.mcfunction
  gm4_cozy_campfires/data/gm4_cozy_campfires/functions/upgrade_marker.mcfunction
Labels: quality-update, tested

#649 Tinkering Compressors: Fix Storage Wipe on Creation
  gm4_tinkering_compressors/data/gm4_tinkering_compressors/functions/create.mcfunction
Labels: fix

#637 Everstone: Add 1.17 Mobs
  gm4_everstone/data/gm4_everstone/tags/entity_types/affected.json
Labels: feature-update, tested

#654 Smelteries 1.17
  gm4_smelteries/data/gm4_smelteries/loot_tables/smelt.json
  gm4_smelteries/data/gm4_smelteries/loot_tables/smeltable_display.json
Labels: feature-update, tested

#641 Xp Storage: Update sneaking check and fix visual bug
  gm4_xp_storage/data/gm4_xp_storage/advancements/join.json
  gm4_xp_storage/data/gm4_xp_storage/functions/deposit_mode_check.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/dump_all.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/dump_level.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/init.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/init_xp.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/main.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/point_report.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/point_report_ray.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/tick.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/withdraw.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/functions/xp_deposit_loop.mcfunction
  gm4_xp_storage/data/gm4_xp_storage/predicates/sneaking.json
Labels: tested, quality-update

#602 Block Compressors: Arbitrary Compression
  gm4_block_compressors/data/gm4/advancements/block_compressors.json
  gm4_block_compressors/data/gm4/advancements/block_compressors_compressed_diet.json
  gm4_block_compressors/data/gm4_block_compressors/functions/compress/16.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/compress/64.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/decompress/16.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/decompress/64.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/init.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/item.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/item/compress.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/item/decompress.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/item/try_compress.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/item/try_decompress.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/functions/process.mcfunction
  gm4_block_compressors/data/gm4_block_compressors/loot_tables/compressed_lore.json
  gm4_block_compressors/pack.mcmeta
Labels: tested, feature-update, fix

#648 Added piglin-chair reverting
  gm4_chairs/data/gm4_chairs/advancements/lightning.json
  gm4_chairs/data/gm4_chairs/functions/lightning/delay.mcfunction
  gm4_chairs/data/gm4_chairs/functions/lightning/revive_chair.mcfunction
  gm4_chairs/data/gm4_chairs/functions/lightning/tag.mcfunction
Labels: tested, feature-update

#657 Beehive Inspectors: Main check to advancement trigger
  gm4_beehive_inspector/data/gm4_beehive_inspector/advancements/break.json
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/find_item.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/init.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/inspect.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/load.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/functions/main.mcfunction
  gm4_beehive_inspector/data/gm4_beehive_inspector/loot_tables/lore.json
Labels: tested, feature-update, quality-update

#608 Adds Vigere Shamir for Shields - Heal when blocking
  gm4_vigere_shamir/data/gm4_metallurgy/tags/functions/check_item_validity.json
  gm4_vigere_shamir/data/gm4_metallurgy/tags/functions/summon_band/barimium.json
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/check_heal.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/check_item_validity.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/heal.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/init.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/load.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/main.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/mark_item_validity.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/revert_health.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/summon_band.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/loot_tables/band.json
  gm4_vigere_shamir/data/gm4_vigere_shamir/predicates/vigere_active.json
  gm4_vigere_shamir/data/load/tags/functions/gm4_vigere_shamir.json
  gm4_vigere_shamir/data/load/tags/functions/load.json
  gm4_vigere_shamir/pack.mcmeta
  gm4_vigere_shamir/pack.png
  gm4_vigere_shamir/pack.svg
Labels: module, submission, server-testing

#628 Rewrite Arborenda for 1.17
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/check_item_validity.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/chop.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/destroy_block.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/destroy_trunk.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/drop_logs.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/fell_acacia.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/fell_birch.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/fell_dark_oak.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/fell_jungle.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/fell_oak.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/fell_spruce.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/init_fell_acacia.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/init_fell_birch.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/init_fell_dark_oak.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/init_fell_jungle.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/init_fell_oak.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/init_fell_spruce.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/main.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/mark_item_validity.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/mark_neighbors.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/mark_neighbors_top.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/modify_axe_durability.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/next_depth.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/summon_band.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/item_modifiers/set_damage.json
  gm4_metallurgy/data/gm4_metallurgy/functions/init.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/tick.mcfunction
Labels: tested, feature-update, quality-update

#630 SCUBA Gear 1.17 Rewrite
  gm4_scuba_gear/data/gm4_scuba_gear/functions/breathe.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/functions/check_gear.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/functions/equipped.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/functions/init.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/functions/load.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/functions/main.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/functions/recipe_check.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/functions/remove_effect.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/loot_tables/items/flippers.json
  gm4_scuba_gear/data/gm4_scuba_gear/loot_tables/items/scuba_helmet.json
  gm4_scuba_gear/data/gm4_scuba_gear/loot_tables/items/scuba_tank.json
  gm4_scuba_gear/data/gm4_scuba_gear/predicates/in_water.json
  gm4_scuba_gear/data/load/tags/functions/gm4_scuba_gear.json
  gm4_scuba_gear/pack.mcmeta
Labels: tested, quality-update

#633 Soul Glass: Consistent beacon behaviour
  gm4_soul_glass/data/gm4_soul_glass/functions/beacon_clock.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/apply_normal_effect.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/apply_strong_effect.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/check.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_1.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_1_strong.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_2.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_2_strong.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_3.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_3_strong.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/level_4.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/effect/update_effects.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/check_finish_smelt.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/furnace/place_blast_furnace.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/main.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/place_soul_glass.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/upgrade_marker_bf.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/functions/upgrade_marker_sg.mcfunction
Labels: tested, quality-update

#636 Fulcio Raycast Fix
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/4_tick.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/active.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/create_block.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/init.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/main.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/functions/ray.mcfunction
  gm4_fulcio_shamir/data/gm4_fulcio_shamir/predicates/holding_fulcio.json
Labels: tested, feature-update

#638 Apple Trees Markers and Raycast Fix
  gm4_apple_trees/data/gm4_apple_trees/functions/chunk/generate_seed.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/chunk/spawn_tree.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/sapling/initialize.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/sapling/restore_data/restore.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/sapling/restore_data/validate_species.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/sapling/validate_species.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/check_clear_space.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/generate.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/orientate.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/branch_0.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/branch_1.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/branch_1a.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/branch_1b.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/leaves_1aa.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/leaves_1ab.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/leaves_1ba.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/layer/place/leaves_1bb.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/check_leaf_validity.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/extract_coordinate.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/select_angle/0_1.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/select_angle/0_3.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/select_angle/2_3.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/select_angle/4_5.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/select_angle/4_7.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/select_angle/6_7.mcfunction
  gm4_apple_trees/data/gm4_apple_trees/functions/tree/leaf/fruiting/select_location/set_coordiante.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/sapling/advance_stage.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/sapling/destroy.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/sapling/place_sapling.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/sapling/process.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/sapling/ray.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/sapling/ray_backup.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/tick.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/tree/analyze_seed.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/tree/generate.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/tree/initialize.mcfunction
  gm4_apple_trees/data/gm4_fruiting_trees/functions/upgrade_marker.mcfunction
Labels: tested, quality-update

#647 Update Display Frames to 1.17
  gm4_display_frames/data/gm4_display_frames/functions/frame/invisible/apply_invisibility.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/frame/invisible/clear_invisibility.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/frame/invisible/create.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/main.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/check_splash.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/kill.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/thrown_potion_tracking/spawn_tracker.mcfunction
  gm4_display_frames/data/gm4_display_frames/functions/tick.mcfunction
  gm4_display_frames/data/gm4_display_frames/tags/entity_types/frame.json
  gm4_display_frames/data/gm4_display_frames/tags/entity_types/potion_tracker.json
Labels: tested, quality-update

#652 Better Fire: Arrows nerfed
  gm4_better_fire/data/gm4_better_fire/functions/arrow.mcfunction
  gm4_better_fire/data/gm4_better_fire/functions/on_fire.mcfunction
  gm4_better_fire/data/gm4_better_fire/loot_tables/entities/flame_arrow/flint.json
Labels: feature-update

#653 Rewrite and enhance the Undead Players module
  gm4_undead_players/data/gm4_undead_players/advancements/death.json
  gm4_undead_players/data/gm4_undead_players/functions/died.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/init.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/init_drowned.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/init_zombie.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/main.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/process_drowning.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/set_drowned_name.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/summon_drowned.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/summon_zombie.mcfunction
  gm4_undead_players/data/gm4_undead_players/item_modifiers/zombie_name.json
  gm4_undead_players/data/gm4_undead_players/loot_tables/drowned_name.json
  gm4_undead_players/data/gm4_undead_players/loot_tables/player_head.json
Labels: tested, feature-update

#655 Standard Crafting 1.17
  gm4_standard_crafting/data/gm4_standard_crafting/functions/recipe_check.mcfunction
  gm4_standard_crafting/data/gm4_standard_crafting/functions/slabs_recipes.mcfunction
  gm4_standard_crafting/data/gm4_standard_crafting/functions/stairs_recipes.mcfunction
Labels: tested, feature-update

#616 Particles Pack: More particles
  gm4_particles_pack/data/gm4_particles_pack/functions/apply_book.mcfunction
  gm4_particles_pack/data/gm4_particles_pack/functions/particle.mcfunction
Labels: tested, feature-update

#659 Audere to use Item Modifiers
  gm4_audere_shamir/data/gm4_audere_shamir/functions/update_netherite.mcfunction
  gm4_audere_shamir/data/gm4_audere_shamir/item_modifiers/update_netherite.json
  gm4_audere_shamir/pack.mcmeta
Labels: quality-update

#619 Spawner minecarts 1.17 update
  gm4_orbis/data/gm4_orbis/functions/structure/spawner_check.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/spawner_default.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/spawner_water.mcfunction
  gm4_orbis/data/gm4_orbis/loot_tables/entities/creeper.json
  gm4_orbis/data/gm4_orbis/loot_tables/entities/drowned.json
  gm4_orbis/data/gm4_orbis/loot_tables/entities/guardian.json
  gm4_orbis/data/gm4_orbis/loot_tables/entities/pufferfish.json
  gm4_orbis/data/gm4_orbis/loot_tables/entities/skeleton.json
  gm4_orbis/data/gm4_orbis/loot_tables/entities/spider.json
  gm4_orbis/data/gm4_orbis/loot_tables/entities/zombie.json
  gm4_orbis/data/gm4_spawner_minecarts/tags/functions/spawner_check.json
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/capture_spawner/enter_minecart.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/capture_spawner/finalize_enter_minecart.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/capture_spawner/spawner_list.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/capture_spawner/vanilla_spawners.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/active_regeneration.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/analyze_consumable_block.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/check_for_consumable_block.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/consume_flower.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/consume_grass.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/consume_normal_flower.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/consume_poisonous_flower.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/decorative_particle.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/detector_rail.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/passive_regeneration.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/rail_checks.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/unloaded_fuel_calculations.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/load.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/main.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/process.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/spawning/spawn_detection.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/tags/blocks/consumable_block.json
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/tags/functions/spawner_check.json
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/tags/functions/spawner_list.json
Labels: feature-update, quality-update

#672 Make Vigere use extra Durability
  gm4_vigere_shamir/data/gm4_vigere_shamir/functions/heal.mcfunction
  gm4_vigere_shamir/data/gm4_vigere_shamir/item_modifiers/use_durability_mainhand.json
  gm4_vigere_shamir/data/gm4_vigere_shamir/item_modifiers/use_durability_offhand.json
  gm4_vigere_shamir/data/gm4_vigere_shamir/predicates/vigere_active.json
  gm4_vigere_shamir/data/gm4_vigere_shamir/predicates/vigere_in_mainhand.json
Labels: feature-update, fix
