Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2022-10, with the labels that each got.

#808 Mob Curing Potion Clerics do not get trades when the Witch has tags
  gm4_mob_curing/data/gm4_mob_curing/functions/cure/witch.mcfunction
Labels: fix

#797 Fix Invalid Minecart Items
  gm4_ender_hoppers/data/gm4_ender_hoppers/functions/machine/destroy_cart.mcfunction
  gm4_ender_hoppers/data/gm4_ender_hoppers/functions/machine/destroy_cart/drop_item.mcfunction
  gm4_ender_hoppers/data/gm4_ender_hoppers/functions/machine/destroy_cart/scan_hoppers.mcfunction
  gm4_ender_hoppers/data/gm4_ender_hoppers/functions/machine/destroy_cart/update_hopper.mcfunction
  gm4_ender_hoppers/data/gm4_ender_hoppers/functions/machine/destroy_cart/update_hopper_minecart.mcfunction
  gm4_liquid_minecarts/data/gm4_liquid_minecarts/functions/machine/destroy_cart.mcfunction
  gm4_liquid_minecarts/data/gm4_liquid_minecarts/functions/machine/destroy_cart/drop_item.mcfunction
  gm4_liquid_minecarts/data/gm4_liquid_minecarts/functions/machine/destroy_cart/scan_hoppers.mcfunction
  gm4_liquid_minecarts/data/gm4_liquid_minecarts/functions/machine/destroy_cart/update_hopper.mcfunction
  gm4_liquid_minecarts/data/gm4_liquid_minecarts/functions/machine/destroy_cart/update_hopper_minecart.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/machine/destroy_cart.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/machine/destroy_cart/drop_item.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/machine/destroy_cart/scan_hoppers.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/machine/destroy_cart/update_hopper.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/machine/destroy_cart/update_hopper_minecart.mcfunction
Labels: fix

#795 Arborenda Enchantment Update
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/active.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/check_item.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/chop.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/destroy_block.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/destroy_trunk.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/main.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/mark_neighbors.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/mark_neighbors_bottom.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/mark_neighbors_top.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/modify_axe_durability.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/next_depth.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/player/analyze_axe.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/player/check_block_drop.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/player/check_for_axe.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/player/chop.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/player/modify_axe_durability.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/check_depth.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/destroy_block.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/destroy_sequenced.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/neighbors/mark.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/neighbors/mark_bottom.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/neighbors/mark_top.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/next_depth.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/item_modifiers/set_damage.json
  gm4_metallurgy/data/gm4_arborenda_shamir/loot_tables/roll_binomial_distribution.json
  gm4_metallurgy/data/gm4_arborenda_shamir/tags/blocks/fungus_foliage.json
  gm4_metallurgy/data/gm4_arborenda_shamir/tags/blocks/trunks.json
  gm4_metallurgy/data/gm4_metallurgy/functions/init.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/tick.mcfunction
Labels: feature-update, server-testing

#814 Make Arborenda Mangrove Compatible
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/player/check_block_drop.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/neighbors/mark.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/functions/trunk/neighbors/mark_bottom.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/tags/blocks/foliage.json
  gm4_metallurgy/data/gm4_arborenda_shamir/tags/blocks/trunks.json
Labels: feature-update

#802 Stop Lumos torch placement if in water
  gm4_lumos_shamir/data/gm4_lumos_shamir/functions/active.mcfunction
Labels: fix
