Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2022-02, with the labels that each got.

#746 Fix spawner minecarts not accepting vanilla spawners without SpawnPotentials
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/capture_spawner/vanilla_spawners.mcfunction
Labels: fix, server-testing

#722 Sweethearts fix for absorption
  gm4_sweethearts/data/gm4_sweethearts/functions/get_health.mcfunction
  gm4_sweethearts/data/gm4_sweethearts/functions/init.mcfunction
  gm4_sweethearts/data/gm4_sweethearts/functions/kill_donor.mcfunction
  gm4_sweethearts/data/gm4_sweethearts/functions/transfer_donor.mcfunction
  gm4_sweethearts/data/gm4_sweethearts/functions/transfer_recipient.mcfunction
  gm4_sweethearts/data/gm4_sweethearts/functions/transferring.mcfunction
  gm4_sweethearts/pack.mcmeta
Labels: tested, fix

#716 Orbis 1.18 part 2
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/functions/spawn.mcfunction
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/functions/spawn/default.mcfunction
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/loot_tables/spawn.json
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/loot_tables/spawn/badlands.json
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/loot_tables/spawn/default.json
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/loot_tables/spawn/desert.json
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/loot_tables/spawn/ocean.json
  gm4_dangerous_dungeons/data/gm4_dangerous_dungeons/loot_tables/spawn/snowy.json
  gm4_orbis/data/gm4_orbis/functions/main.mcfunction
  gm4_orbis/data/gm4_orbis/functions/metachunk/generate.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/chest_dungeon.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/chest_tower.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/chunk.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/spawn_attempt.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/spawner_default.mcfunction
  gm4_orbis/data/gm4_orbis/functions/structure/spawner_water.mcfunction
  gm4_orbis/data/gm4_orbis/loot_tables/entities/glow_squid.json
  gm4_tower_structures/data/gm4_tower_structures/functions/spawn.mcfunction
  gm4_tower_structures/data/gm4_tower_structures/functions/spawn/badlands.mcfunction
  gm4_tower_structures/data/gm4_tower_structures/functions/spawn/default.mcfunction
  gm4_tower_structures/data/gm4_tower_structures/functions/spawn/desert.mcfunction
  gm4_tower_structures/data/gm4_tower_structures/functions/spawn/ocean.mcfunction
  gm4_tower_structures/data/gm4_tower_structures/functions/spawn/snowy.mcfunction
  gm4_tower_structures/data/gm4_tower_structures/loot_tables/spawn.json
  gm4_tower_structures/data/gm4_tower_structures/loot_tables/spawn/badlands.json
  gm4_tower_structures/data/gm4_tower_structures/loot_tables/spawn/default.json
  gm4_tower_structures/data/gm4_tower_structures/loot_tables/spawn/desert.json
  gm4_tower_structures/data/gm4_tower_structures/loot_tables/spawn/ocean.json
  gm4_tower_structures/data/gm4_tower_structures/loot_tables/spawn/snowy.json
  gm4_tower_structures/data/gm4_tower_structures/structures/acacia1.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/badlands4.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/cobblestone1.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/cobblestone2.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/diorite1.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/diorite2.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/granite1.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/raft.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/sandstone1.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/spruce1.nbt
Labels: feature-update, fix
