Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2022-01, with the labels that each got.

#727 Orb of Ankou - Turn off bubbly particles
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/functions/player.mcfunction
Labels: quality-update

#726 Fix some CMD from Sunken Treasure
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/guidebook/add_pages.mcfunction
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/loot_tables/soul_essence/feigning.json
  gm4_sunken_treasure/data/gm4_sunken_treasure/loot_tables/gameplay/treasure_loot/gravel.json
  gm4_sunken_treasure/data/gm4_sunken_treasure/loot_tables/gameplay/treasure_loot/sand.json
Labels: fix

#732 Remove trailing spaces
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/functions/pneumas/feigning/move_away.mcfunction
Labels: fix

#729 Prevents Desire Lines from breaking moss carpet
  gm4_desire_lines/data/gm4_desire_lines/functions/path.mcfunction
Labels: fix, server-testing

#712 LiaB: Adds Liquid Tanks compat
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/brew/lingering.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/brew/splash.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/brewing_stand/texture_connector/check_structure.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/item_drain.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/item_fill.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/item_fill/lightning_bottle.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/liquid_init/lightning.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/remove_liquid_tags.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/tank_init.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/util/lightning.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/util_below.mcfunction
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/entities/illusioner.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/lingering_bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/lingering_potion_of_blindness.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/splash_bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/lingering.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/lingering/bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/splash.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/technical/brewing_stand/splash/bottle_of_lightning.json
  gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/predicates/on_fire.json
  gm4_lightning_in_a_bottle/data/gm4_liquid_tanks/tags/functions/item_drain.json
  gm4_lightning_in_a_bottle/data/gm4_liquid_tanks/tags/functions/item_fill.json
  gm4_lightning_in_a_bottle/data/gm4_liquid_tanks/tags/functions/remove_liquid_tags.json
  gm4_lightning_in_a_bottle/data/gm4_liquid_tanks/tags/functions/tank_init.json
  gm4_lightning_in_a_bottle/data/gm4_liquid_tanks/tags/functions/util_below.json
  gm4_potion_liquids/data/gm4_potion_liquids/functions/util_above.mcfunction
Labels: feature-update, server-testing

#713 Zauber Cauldrons 1.18
  gm4_zauber_cauldrons/data/gm4_trades/tags/functions/register_trades.json
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/extra_items/catch_possessed_items.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/structure/use_extra_items.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/load.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/armor_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/boots/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/armor_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/chestplate/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/armor_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/helmet/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/armor_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/attack_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/health_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/leggings/speed_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/armor/use_cauldron.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/chorus/blurry_wormhole.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/chorus/precise_wormhole.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/effects/instant_damage.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/effects/instant_health.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/effects/jump_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/effects/poison.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/effects/regeneration.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/effects/speed.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/effects/strength.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/crystals/use_cauldron.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/drinkable/instant_damage.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/drinkable/instant_health.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/drinkable/jump_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/drinkable/poison.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/drinkable/regeneration.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/drinkable/speed.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/drinkable/strength.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/environmental_effects/jump_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/instant_damage.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/instant_health.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/jump_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/poison.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/regeneration.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/speed.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/strength.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/instant_damage.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/instant_health.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/jump_boost.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/poison.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/regeneration.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/speed.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/strength.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/use_cauldron.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/precursors/enchanted_prismarine_shard.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/wandering_trader/register_trades.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/wandering_trader/enchanted_prismarine_shard.json
  gm4_zauber_cauldrons/data/load/tags/functions/gm4_zauber_cauldrons.json
  gm4_zauber_cauldrons/pack.mcmeta
Labels: feature-update, server-testing

#740 add glow squid below y30
  gm4_sunken_treasure/data/gm4_sunken_treasure/functions/spawn_entity.mcfunction
  gm4_sunken_treasure/data/gm4_sunken_treasure/loot_tables/gameplay/treasure_loot/gravel.json
  gm4_sunken_treasure/data/gm4_sunken_treasure/loot_tables/gameplay/treasure_loot/sand.json
Labels: feature-update, server-testing

#735 Lumos 1.17/1.18 Update
  gm4_lumos_shamir/data/gm4_lumos_shamir/predicates/check_air.json
  gm4_lumos_shamir/data/gm4_lumos_shamir/tags/blocks/torch_placeable.json
Labels: feature-update, server-testing

#731 Make Ender Bolt ignore pets
  gm4_metallurgy/data/gm4_ender_bolt_shamir/advancements/join.json
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/id/assign_pet.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/id/assign_player.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/infection/active.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/infection/check_ignore_list.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/infection/end.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/infection/infect.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/infection/spread.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/functions/infection/start.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/tags/entity_types/pets.json
  gm4_metallurgy/data/gm4_metallurgy/functions/init.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/main.mcfunction
Labels: feature-update, server-testing

#730 [Vibro Shamir] Increases timing between jump boost levels by 2t
  gm4_metallurgy/data/gm4_vibro_shamir/functions/jump.mcfunction
Labels: fix, server-testing

#728 Tunnel Bores 1.18
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/check_cart_environment.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/destroy.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/functions/bore/item_consumption/rail/place_rail.mcfunction
  gm4_tunnel_bores/data/gm4_tunnel_bores/loot_tables/bore.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/loot_tables/bore_components.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/loot_tables/tunnel_bore.json
  gm4_tunnel_bores/data/gm4_tunnel_bores/tags/blocks/rail_replacable.json
Labels: feature-update, server-testing

#724 Animi Orbs Of Ankou
  gm4_orb_of_ankou/data/gm4_animi_shamir/functions/mark_orb_of_ankou.mcfunction
  gm4_orb_of_ankou/data/gm4_animi_shamir/tags/functions/mark_item_validity.json
Labels: feature-update, server-testing
