Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2022-04, with the labels that each got.

#752 Rope Ladders Module
  contributors.json
  gm4_rope_ladders/data/gm4/advancements/root.json
  gm4_rope_ladders/data/gm4/advancements/rope_ladders.json
  gm4_rope_ladders/data/gm4_rope_ladders/advancements/right_click_detection.json
  gm4_rope_ladders/data/gm4_rope_ladders/functions/init.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/load.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/main.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/break_floating_ladders/break_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/break_floating_ladders/scan_column/init.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/break_floating_ladders/scan_column/loop.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/detect_ladder_raycast/found.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/detect_ladder_raycast/init.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/detect_ladder_raycast/ray.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/interact_right_click_detection.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/place_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/place_water_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/scan_column/found.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/scan_column/init.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/scan_column/loop.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/detect_ladder_raycast/found.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/detect_ladder_raycast/init.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/detect_ladder_raycast/ray.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/display_particles.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/rcd_manager/loop.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/rcd_manager/process.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/rcd_manager/spawn_rcd.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/player/as.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/player/broke_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/player/holding_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/tick.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/item_modifiers/minus_one.json
  gm4_rope_ladders/data/gm4_rope_ladders/predicates/holding_ladder.json
  gm4_rope_ladders/data/gm4_rope_ladders/tags/blocks/ladder_scan.json
  gm4_rope_ladders/data/gm4_rope_ladders/tags/blocks/valid_replace.json
  gm4_rope_ladders/data/load/tags/functions/gm4_rope_ladders.json
  gm4_rope_ladders/data/load/tags/functions/load.json
  gm4_rope_ladders/pack.mcmeta
  gm4_rope_ladders/pack.png
  gm4_rope_ladders/pack.svg
Labels: tested, submission

#765 Add Dripleaf Filters
  gm4_dripleaf_filters/data/gm4_dripleaf_filters/functions/check_hopper_filter.mcfunction
  gm4_dripleaf_filters/data/gm4_dripleaf_filters/functions/deposit_item.mcfunction
  gm4_dripleaf_filters/data/gm4_dripleaf_filters/functions/init.mcfunction
  gm4_dripleaf_filters/data/gm4_dripleaf_filters/functions/load.mcfunction
  gm4_dripleaf_filters/data/gm4_dripleaf_filters/functions/main.mcfunction
  gm4_dripleaf_filters/data/gm4_dripleaf_filters/functions/match_item.mcfunction
  gm4_dripleaf_filters/data/gm4_dripleaf_filters/functions/on_leaf.mcfunction
  gm4_dripleaf_filters/data/load/tags/functions/gm4_dripleaf_filters.json
  gm4_dripleaf_filters/data/load/tags/functions/load.json
  gm4_dripleaf_filters/pack.mcmeta
Labels: module, needs-testing

#758 Tweak end fishing reel in timer to match vanilla fishing
  gm4_end_fishing/data/gm4_end_fishing/functions/process.mcfunction
Labels: fix
