Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2023-09, with the labels that each got.

#789 New mountaineering module
  contributors.json
  gm4_mountaineering/README.md
  gm4_mountaineering/beet.yaml
  gm4_mountaineering/data/gm4/advancements/root.json
  gm4_mountaineering/data/gm4/advancements/ski.json
  gm4_mountaineering/data/gm4/advancements/ski_fast.json
  gm4_mountaineering/data/gm4_custom_crafters/tags/functions/check_recipes.json
  gm4_mountaineering/data/gm4_mountaineering/functions/check_recipes.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/climbing_effects/add_climb_effects.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/climbing_effects/damage_shulkers.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/climbing_effects/reset_shulker_peek.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/fast_main.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/get_velocity.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/init.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/main.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/new_crampons.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/new_skis.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/player_fast_main.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/player_main.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/pole_effects/poles_equipped.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/check_snowy_block.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/downhill_ski_speed/add_downhill_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/downhill_ski_speed/check_downhill_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/downhill_ski_speed/remove_downhill_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/flat_ski_speed/add_flat_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/flat_ski_speed/remove_flat_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/ski_off_snow_slowness/add_off_snow_slowness.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/ski_off_snow_slowness/remove_off_snow_slowness.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/skis_equipped.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/skis_removed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/steep_downhill_ski_speed/add_steep_downhill_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/steep_downhill_ski_speed/check_steep_downhill_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/ski_effects/steep_downhill_ski_speed/remove_steep_downhill_ski_speed.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/loot_tables/crafting/crampons.json
  gm4_mountaineering/data/gm4_mountaineering/loot_tables/crafting/poles.json
  gm4_mountaineering/data/gm4_mountaineering/loot_tables/crafting/skis.json
  gm4_mountaineering/data/gm4_mountaineering/loot_tables/items/crampons.json
  gm4_mountaineering/data/gm4_mountaineering/loot_tables/items/poles.json
  gm4_mountaineering/data/gm4_mountaineering/loot_tables/items/skis.json
  gm4_mountaineering/data/gm4_mountaineering/predicates/hands_empty.json
  gm4_mountaineering/data/gm4_mountaineering/predicates/high_entity.json
  gm4_mountaineering/data/gm4_mountaineering/predicates/holding_poles.json
  gm4_mountaineering/data/gm4_mountaineering/predicates/on_snowy_block.json
  gm4_mountaineering/data/gm4_mountaineering/predicates/on_snowy_block_or_air.json
  gm4_mountaineering/data/gm4_mountaineering/predicates/wearing_crampons.json
  gm4_mountaineering/data/gm4_mountaineering/predicates/wearing_skis.json
  gm4_mountaineering/data/gm4_mountaineering/tags/blocks/climbable_blocks.json
  gm4_mountaineering/data/gm4_mountaineering/tags/blocks/snowy_blocks.json
  gm4_mountaineering/images/mountaineering.webp
  gm4_mountaineering/pack.png
Labels: module, submission

#881 Rope Ladders Update
  gm4_rope_ladders/data/gm4_rope_ladders/advancements/right_click_detection.json
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/break_floating_ladders/break_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/break_floating_ladders/scan_column/init.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/detect_ladder_raycast/ray.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/place_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/ladder_placement/scan_column/loop.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/detect_ladder_raycast/found.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/detect_ladder_raycast/ray.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/display_particles.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/rcd_manager/loop.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/rcd_manager/process.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/mechanics/right_click_detection/rcd_manager/spawn_rcd.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/player/as.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/functions/player/broke_ladder.mcfunction
  gm4_rope_ladders/data/gm4_rope_ladders/tags/blocks/ladder_scan.json
  gm4_rope_ladders/data/gm4_rope_ladders/tags/blocks/valid_replace.json
Labels: tested, quality-update

#903 Chairs: Make dismounting reliant on a tag instead of a team
  gm4_chairs/data/gm4_chairs/advancements/hit.json
  gm4_chairs/data/gm4_chairs/functions/create_chair.mcfunction
  gm4_chairs/data/gm4_chairs/predicates/sitting_in_chair.json
Labels: quality-update
