Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2023-12, with the labels that each got.

#924 Fix AEC duration in overlay_18
  gm4_dripleaf_launchers/overlay_18/data/gm4_dripleaf_launchers/functions/launch.mcfunction
  gm4_mysterious_midnights/overlay_18/data/gm4_falling_stars/functions/falling_star/spawn.mcfunction
  gm4_orb_of_ankou/overlay_18/data/gm4_orb_of_ankou/functions/soul_forge/entities/withering_magic.mcfunction
  gm4_tnt_landmines/overlay_18/data/gm4_tnt_landmines/functions/blowup/safe.mcfunction
  gm4_zauber_cauldrons/overlay_18/data/gm4_zauber_cauldrons/functions/recipes/flowers/luck.mcfunction
  gm4_zauber_cauldrons/overlay_18/data/gm4_zauber_cauldrons/functions/recipes/flowers/poison.mcfunction
  gm4_zauber_cauldrons/overlay_18/data/gm4_zauber_cauldrons/functions/recipes/potions/environmental_effects/instant_damage.mcfunction
  gm4_zauber_cauldrons/overlay_18/data/gm4_zauber_cauldrons/functions/recipes/potions/environmental_effects/instant_health.mcfunction
  gm4_zauber_cauldrons/overlay_18/data/gm4_zauber_cauldrons/functions/recipes/potions/environmental_effects/regeneration.mcfunction
Labels: fix

#920 Double Doors: Close doors automatically after a player walks through
  contributors.json
  gm4_double_doors/README.md
  gm4_double_doors/beet.yaml
  gm4_double_doors/data/gm4_double_doors/functions/auto_toggle_marker/find.mcfunction
  gm4_double_doors/data/gm4_double_doors/functions/auto_toggle_marker/maintain.mcfunction
  gm4_double_doors/data/gm4_double_doors/functions/auto_toggle_marker/player_departed.mcfunction
  gm4_double_doors/data/gm4_double_doors/functions/auto_toggle_marker/select_material.mcfunction
  gm4_double_doors/data/gm4_double_doors/functions/init.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/left/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/right/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/left/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/right/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/left/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/right/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/left/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/right/initialize_auto_toggle_marker.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_east/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_east/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_west/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_west/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_east/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_east/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_west/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_west/toggle.mcfunction
  gm4_double_doors/generate.py
  gm4_double_doors/pack.png
  gm4_double_doors/pack.svg
  gm4_double_doors/raw/sound_names.csv
Labels: feature-update, needs-testing

#913 Add support for trapped hanging signs
  gm4_trapped_signs/beet.yaml
  gm4_trapped_signs/data/gm4_trapped_signs/functions/activate.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/complete.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/deactivate.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/destroy.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/machine/assign_tag.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/machine/create_secret_trapped_sign.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/machine/create_trapped_sign.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/machine/destroy.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/machine/drop_item.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/ray.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/recipes/secret_trapped_sign.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/functions/recipes/trapped_sign.mcfunction
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_acacia_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_bamboo_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_birch_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_cherry_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_crimson_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_dark_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_jungle_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_mangrove_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_spruce_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/secret_trapped_warped_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_acacia_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_bamboo_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_birch_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_cherry_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_crimson_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_dark_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_jungle_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_mangrove_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_spruce_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/crafting/trapped_warped_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_acacia_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_bamboo_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_birch_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_cherry_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_crimson_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_dark_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_jungle_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_mangrove_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_spruce_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/secret_trapped_warped_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_acacia_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_bamboo_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_birch_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_cherry_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_crimson_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_dark_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_jungle_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_mangrove_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_oak_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_spruce_sign.json
  gm4_trapped_signs/data/gm4_trapped_signs/loot_tables/items/trapped_warped_sign.json
  gm4_trapped_signs/generate_types.py
Labels: tested, feature-update

#926 Fix ender bolt tridents in the ground not spreading
  gm4_metallurgy/data/gm4_metallurgy/functions/main.mcfunction
  gm4_metallurgy/overlay_26/data/gm4_metallurgy/functions/main.mcfunction
Labels: fix

#927 Update soul glass block state predicate for 1.20.2
  gm4_soul_glass/overlay_18/data/gm4_soul_glass/predicates/has_beam.json
Labels: fix

#929 Fix Custom Cart Placement
  gm4_ender_hoppers/beet.yaml
  gm4_ender_hoppers/overlay_26/data/gm4_ender_hoppers/functions/machine/verify_place_cart.mcfunction
  gm4_liquid_minecarts/beet.yaml
  gm4_liquid_minecarts/overlay_26/data/gm4_liquid_minecarts/functions/machine/verify_place_cart.mcfunction
  gm4_tunnel_bores/beet.yaml
  gm4_tunnel_bores/overlay_26/data/gm4_tunnel_bores/functions/machine/create_cart.mcfunction
  gm4_tunnel_bores/overlay_26/data/gm4_tunnel_bores/functions/machine/verify_place_cart.mcfunction
  poetry.lock
  pyproject.toml
Labels: fix
