Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2023-08, with the labels that each got.

#892 Pirate Translations
  gm4_tower_structures/data/gm4_tower_structures/structures/spawner/ship/skeleton_bow_down.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/spawner/ship/skeleton_bow_side.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/spawner/ship/skeleton_bow_up.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/spawner/ship/skeleton_sword_down.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/spawner/ship/skeleton_sword_side.nbt
  gm4_tower_structures/data/gm4_tower_structures/structures/spawner/ship/skeleton_sword_up.nbt
Labels: tested, fix

#853 Dripleaf Launchers
  gm4_dripleaf_launchers/README.md
  gm4_dripleaf_launchers/beet.yaml
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/functions/check.mcfunction
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/functions/init.mcfunction
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/functions/launch.mcfunction
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/functions/main.mcfunction
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/functions/tick.mcfunction
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/predicates/dripleaf_no_tilt.json
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/predicates/dripleaf_tilted.json
  gm4_dripleaf_launchers/data/gm4_dripleaf_launchers/predicates/dripleaf_triggered.json
Labels: module, tested

#890 Add Double Doors
  gm4_double_doors/README.md
  gm4_double_doors/beet.yaml
  gm4_double_doors/data/gm4_double_doors/functions/init.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/advancements/use_door.json
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/get_hinge.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/left/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/right/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/east/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/get_facing.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/get_lower_half.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/get_hinge.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/left/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/right/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/north/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/get_hinge.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/left/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/right/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/south/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/get_hinge.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/left/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/left/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/right/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/door/west/right/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/ray.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_east/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_east/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_west/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/north_west/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_east/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_east/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_west/check_neighbours.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/trapdoor/south_west/toggle.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/functions/use_door.mcfunction
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/east/left/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/east/left/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/east/right/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/east/right/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/north/left/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/north/left/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/north/right/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/north/right/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/south/left/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/south/left/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/south/right/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/south/right/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/west/left/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/west/left/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/west/right/closed.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/door/west/right/open.snbt
  gm4_double_doors/data/gm4_double_doors/templates/structures/test.snbt
  gm4_double_doors/generate.py
  poetry.lock
  pyproject.toml
Labels: module
