Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2023-03, with the labels that each got.

#855 Fix module releases being incorrectly named
  beet-release.yaml
  gm4/plugins/output.py
Labels: fix

#849 add turtle helmets to applicable shamirs
  gm4_metallurgy/data/gm4_defuse_shamir/functions/mark_item_validity.mcfunction
  gm4_weighted_armour/data/gm4_helious_shamir/functions/mark_item_validity.mcfunction
Labels: feature-update

#851 [CC Lib] Fix local builds of modules using vanilla item tags
  lib_machines/generate_item_tags.py
Labels: fix

#847 Module Marketing Readmes
  beet-release.yaml
  gm4/commands.py
  gm4/plugins/manifest.py
  gm4/plugins/output.py
  gm4/plugins/readme_generator.py
  gm4_bat_grenades/README.md
  gm4_better_armour_stands/README.md
  gm4_better_armour_stands/beet.yaml
  gm4_better_armour_stands/images/better_armour_stands.webp
  gm4_chairs/README.md
  gm4_chairs/beet.yaml
  gm4_crossbow_cartridges/README.md
  gm4_crossbow_cartridges/beet.yaml
  gm4_crossbow_cartridges/images/crossbow_cartridges.webp
  gm4_note_block_interface/README.md
  gm4_undead_players/README.md
  gm4_ziprails/README.md
  gm4_ziprails/beet.yaml
Labels: quality-update

#840 Add spore blossom to appropriate block tags.
  base/data/gm4/tags/blocks/foliage.json
  base/data/gm4/tags/blocks/no_collision.json
Labels: fix

#834 Fix Relocator Advancement Grant
  gm4_relocators/data/gm4/advancements/relocators.json
  gm4_relocators/data/gm4_relocators/functions/pick_up/get_data.mcfunction
Labels: fix

#846 Metallurgy 1.19.3 Mould Visibility Hotfix
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/add_metal/initialize.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/check_mould_creation.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/create_mould.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/sustain_mould.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/main.mcfunction
Labels: tested, fix
