Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2023-06, with the labels that each got.

#878 Intro Toast Visibility
  base/data/gm4/advancements/intro_song/root_display.json
  base/data/gm4/advancements/intro_song/welcome_toast.json
  base/data/gm4/functions/intro_song/main.mcfunction
Labels: fix

#827 Crossbow Cartridges: Add Beehives
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/check_projectile.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/functions/projectile/beehive.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/item_modifiers/remove_bee.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicates/items/beehive.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/tags/items/valid_items.json
Labels: feature-update, needs-testing

#839 Fix multiple fusing rituals breaking each other
  gm4_orb_of_ankou/data/gm4_orb_of_ankou/functions/soul_forge/wither_roses/steps.mcfunction
Labels: fix

#880 Animi Item Loss Fix
  gm4_animi_shamir/data/gm4_animi_shamir/functions/player/wait_for_respawn.mcfunction
Labels: fix

#852 Shapeless Portals
  gm4_shapeless_portals/README.md
  gm4_shapeless_portals/beet.yaml
  gm4_shapeless_portals/data/gm4_shapeless_portals/advancements/light_portal.json
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/init.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/portal_found.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/portal_lit.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/raycast.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/x/build.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/x/check_location.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/x/flood_fill.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/z/build.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/z/check_location.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/functions/z/flood_fill.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/predicates/portal_validity_x.json
  gm4_shapeless_portals/data/gm4_shapeless_portals/predicates/portal_validity_z.json
  gm4_shapeless_portals/data/gm4_shapeless_portals/tags/blocks/portal_block.json
  gm4_shapeless_portals/images/shapeless_portals.png
Labels: module

#887 Fix Arborenda Unbreaking Behaviour
  gm4_metallurgy/data/gm4_arborenda_shamir/loot_tables/roll_binomial_distribution.json
Labels: fix
