Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2024-03, with the labels that each got.

#976 Infinitas Shamir: Adds 2 packtests
  gm4_metallurgy/data/gm4_infinitas_shamir/tests/check_empty_pickup.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/tests/check_unsmoosh_after_use.mcfunction
Labels: tests

#982 Vertical Rails: Advancement grant fix
  gm4_vertical_rails/data/gm4_vertical_rails/functions/tick.mcfunction
  gm4_vertical_rails/data/gm4_vertical_rails/structures/test_track.nbt
  gm4_vertical_rails/data/gm4_vertical_rails/tests/go_up.mcfunction
  gm4_vertical_rails/overlay_26/data/gm4_vertical_rails/functions/main.mcfunction
  gm4_vertical_rails/pack.mcmeta
Labels: fix

#974 Calling Bell: Check valid trader spawn location
  gm4_calling_bell/data/gm4_calling_bell/functions/bell/ray/loop.mcfunction
  gm4_calling_bell/data/gm4_calling_bell/functions/bell/ray/setup.mcfunction
  gm4_calling_bell/data/gm4_calling_bell/functions/trader/summon.mcfunction
  gm4_calling_bell/data/gm4_calling_bell/predicates/trader_hitbox_no_collision.json
  gm4_calling_bell/data/gm4_calling_bell/tests/call_blocked.mcfunction
Labels: fix, server-testing

#979 Zauber Cauldrons: Fix Rabbit Teleportation Easter Egg
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/rabbit_teleportation.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/structure/validate/liquid.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/tests/rabbit_teleportation.mcfunction
Labels: fix, server-testing

#973 Boots of Ostara: Allow Offhand Item Usage When On Armor Stands
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/functions/armor_stand_convert.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/armor_stand_grass.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicates/armor_stand_moss.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/tests/armor_stand_both.mcfunction
Labels: feature-update, server-testing

#975 Infinitas Shamir: Various checks
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/pickup_fish.json
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/pickup_mainhand.json
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/pickup_offhand.json
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/place.json
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/place_mainhand.json
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/place_offhand.json
  gm4_metallurgy/data/gm4_infinitas_shamir/functions/clock/inventory_check.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/functions/debug/clear.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/functions/delayed_replace/fish.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/functions/delayed_replace/fish/mainhand_check.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/functions/delayed_replace/fish/offhand_check.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/functions/delayed_replace/water.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/functions/water/place.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/predicates/mainhand/after/water_advancement.json
  gm4_metallurgy/data/gm4_infinitas_shamir/predicates/offhand/after/water_advancement.json
  gm4_metallurgy/data/gm4_metallurgy/functions/tick.mcfunction
Labels: fix, server-testing

#949 Guidebook Tweaks
  gm4_block_compressors/data/gm4_block_compressors/guidebook/block_compressors.json
  gm4_block_compressors/overlay_26/data/gm4_block_compressors/guidebook/block_compressors.json
  gm4_guidebook/data/gm4_guidebook/functions/lecterns/section/check_page.mcfunction
  gm4_guidebook/data/gm4_guidebook/functions/lecterns/section/update/refresh/jump.mcfunction
  gm4_guidebook/generate_guidebooks.py
  gm4_liquid_tanks/data/gm4_liquid_tanks/gm4_recipes/liquid_tank.json
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/guidebook/zauber_cauldrons.json
Labels: feature-update

#984 Upload artifact of failing test worlds
  .github/workflows/main.yml
Labels: tool

#990 Add Github Action Summary
  gm4/plugins/annotations.py
  gm4/plugins/manifest.py
  gm4/plugins/output.py
Labels: tool

#989 lib trees: Reduce selectors in tick
  lib_trees/beet.yaml
  lib_trees/data/gm4_trees/functions/load.mcfunction
  lib_trees/data/gm4_trees/functions/main.mcfunction
  lib_trees/data/gm4_trees/functions/tick.mcfunction
Labels: quality-update, server-testing

#986 More tests
  base/data/gm4/structures/test_box.nbt
  base/data/gm4/structures/test_platform_large.nbt
  gm4/plugins/test.py
  gm4_mending_tanks/data/gm4_mending_tanks/tests/repair_item.mcfunction
  gm4_metallurgy/data/gm4_arborenda_shamir/tests/chop.mcfunction
  gm4_metallurgy/data/gm4_defuse_shamir/tests/creeper_defused.mcfunction
  gm4_metallurgy/data/gm4_ender_bolt_shamir/tests/infect_and_spread.mcfunction
  gm4_metallurgy/data/gm4_gemini_shamir/predicates/test_is_baby.json
  gm4_metallurgy/data/gm4_gemini_shamir/tests/breed.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/tests/check_empty_pickup.mcfunction
  gm4_metallurgy/data/gm4_infinitas_shamir/tests/check_unsmoosh_after_use.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/structures/test_casting.nbt
  gm4_metallurgy/data/gm4_metallurgy/tests/cast_add_lumps.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/tests/cast_create_and_destroy.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/tests/cast_mundane.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/tests/cast_overheat.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/tests/cast_successful.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/tests/smoosh.mcfunction
  gm4_metallurgy/data/gm4_musical_shamir/tests/gain_buff.mcfunction
  gm4_mob_curing/data/gm4_mob_curing/tests/cow_to_mooshroom.mcfunction
  gm4_mob_curing/data/gm4_mob_curing/tests/witch_to_potion_cleric.mcfunction
  gm4_mob_curing/data/gm4_mob_curing/tests/ziglin_to_pig.mcfunction
  gm4_mob_curing/data/gm4_mob_curing/tests/ziglin_to_piglin.mcfunction
  gm4_mob_curing/data/gm4_mob_curing/tests/zoglin_to_hoglin.mcfunction
  gm4_note_block_interface/data/gm4_note_block_interface/tests/play_note.mcfunction
  gm4_note_block_interface/data/gm4_note_block_interface/tests/tune_down.mcfunction
  gm4_note_block_interface/data/gm4_note_block_interface/tests/tune_up.mcfunction
  gm4_percurro_shamir/data/gm4_percurro_shamir/tests/attack_player.mcfunction
  gm4_phantom_scarecrows/data/gm4_phantom_scarecrows/tests/kill_phantom.mcfunction
  gm4_pig_tractors/data/gm4_pig_tractors/tests/harvest_carrots.mcfunction
  gm4_pig_tractors/data/gm4_pig_tractors/tests/plant_carrots.mcfunction
  gm4_pig_tractors/data/gm4_pig_tractors/tests/till_soil.mcfunction
  gm4_potion_swords/data/gm4_potion_swords/tests/convert_wither_skeleton.mcfunction
  gm4_potion_swords/data/gm4_potion_swords/tests/inflict_absorption.mcfunction
  gm4_potion_swords/data/gm4_potion_swords/tests/inflict_invisibility.mcfunction
  gm4_potion_swords/data/gm4_potion_swords/tests/inflict_slowness.mcfunction
  gm4_potion_swords/data/gm4_potion_swords/tests/inflict_wither.mcfunction
  gm4_record_crafting/data/gm4_record_crafting/tests/craft_music_disc_13.mcfunction
  gm4_relocators/data/gm4_relocators/tests/craft_relocator.mcfunction
  gm4_relocators/data/gm4_relocators/tests/move_chest.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/tests/craft_flippers.mcfunction
  gm4_scuba_gear/data/gm4_scuba_gear/tests/use_helmet_and_tank.mcfunction
  gm4_shapeless_portals/data/gm4_shapeless_portals/tests/create_1x2_portal.mcfunction
  gm4_smelteries/data/gm4_smelteries/tests/construct_and_use.mcfunction
  gm4_soul_glass/data/gm4_soul_glass/tests/smelt_soul_glass.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/tests/capture_spawner.mcfunction
Labels: tests
