Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2024-09, with the labels that each got.

#1022 Undye Wolf Armor with Washing Tanks
  gm4_washing_tanks/data/gm4_washing_tanks/tags/item/armour.json
Labels: feature-update

#1020 Add Tuff Bricks to Forming Press
  gm4_forming_press/data/gm4_forming_press/function/recipes/brick_recipes.mcfunction
  gm4_forming_press/data/gm4_forming_press/loot_table/crafting/tuff_bricks.json
Labels: feature-update

#992 Mountaineering: fix NBT not being saved when crafting new skis and crampons
  gm4_mountaineering/data/gm4_mountaineering/functions/check_recipes.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/main.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/new_crampons.mcfunction
  gm4_mountaineering/data/gm4_mountaineering/functions/new_skis.mcfunction
Labels: fix

#1030 Add weld rules to yellow shulker box
  lib_forceload/data/minecraft/loot_table/blocks/yellow_shulker_box.json
Labels: fix

#1039 Add 1.21 Blocks & Entities
  base/data/gm4/tags/block/full_collision.json
  gm4_balloon_animals/animals.csv
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/function/check_projectile.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/function/projectile/wind_charge.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/function/projectile/wind_charge_kill.mcfunction
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/guidebook/crossbow_cartridges.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/predicate/items/wind_charge.json
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/tags/item/valid_items.json
Labels: feature-update

#1042 More BoO Conversions and Dual Wielding
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/function/armor_stand_convert.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/function/convert.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/function/init.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/function/main.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/function/player_convert.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicate/armor_stand_grass.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicate/armor_stand_moss.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicate/holding_grass.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/predicate/holding_moss.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/tags/block/mycelium_replaceable.json
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/test/armor_stand_both.mcfunction
  gm4_boots_of_ostara/data/gm4_boots_of_ostara/test/armor_stand_both_backwards.mcfunction
Labels: feature-update

#1041 Separate Bat Leather into separate loot table
  gm4_bat_grenades/data/gm4_bat_grenades/loot_table/items/bat_leather.json
  gm4_bat_grenades/data/minecraft/loot_table/entities/bat.json
Labels: quality-update

#1052 Fix Typo in Double Doors (Fix #1051)
  gm4_double_doors/README.md
  gm4_double_doors/beet.yaml
  gm4_double_doors/translations.csv
Labels: fix

#1049 Fix Typo in Mysterious Midnights Description
  gm4_mysterious_midnights/beet.yaml
Labels: fix
