Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2024-01, with the labels that each got.

#928 Auto Crafting: Fix Recipe Shape Update Advancement
  gm4_auto_crafting/beet.yaml
  gm4_auto_crafting/overlay_26/data/gm4_auto_crafting/advancements/open_auto_crafter.json
Labels: fix

#935 Add undead players and animi shamir compatibility
  gm4_animi_shamir/beet.yaml
  gm4_animi_shamir/data/gm4_animi_shamir/advancements/death.json
  gm4_animi_shamir/data/gm4_animi_shamir/advancements/join.json
  gm4_animi_shamir/data/gm4_animi_shamir/functions/player/upon_death.mcfunction
  gm4_animi_shamir/data/gm4_player_death/tags/functions/soul_bound.json
  gm4_undead_players/beet.yaml
  gm4_undead_players/data/gm4_player_death/tags/functions/grave.json
  gm4_undead_players/data/gm4_undead_players/functions/died.mcfunction
  gm4_undead_players/data/gm4_undead_players/functions/init.mcfunction
  lib_player_death/LICENSE.md
  lib_player_death/README.md
  lib_player_death/beet.yaml
  lib_player_death/data/gm4_player_death/advancements/death.json
  lib_player_death/data/gm4_player_death/functions/death.mcfunction
  lib_player_death/data/gm4_player_death/functions/load.mcfunction
  lib_player_death/data/gm4_player_death/tags/functions/_private/death.json
Labels: fix, quality-update

#937 Allow lib_player_heads to Create Unstackable Player Heads
  lib_player_heads/README.md
  lib_player_heads/beet.yaml
  lib_player_heads/data/gm4_player_heads/functions/call_loot_table.mcfunction
  lib_player_heads/data/gm4_player_heads/functions/found_match.mcfunction
  lib_player_heads/data/gm4_player_heads/functions/repair_with_name.mcfunction
  lib_player_heads/data/gm4_player_heads/functions/repair_with_texture.mcfunction
  lib_player_heads/example_use/data/gm4_example_pack/functions/init.mcfunction
  lib_player_heads/example_use/data/gm4_example_pack/loot_tables/example_head_1.json
  lib_player_heads/example_use/data/gm4_example_pack/loot_tables/example_head_2.json
Labels: feature-update, library

#941 Zauber Cauldrons: Fix Edge-Case Causing Leftover Custom Liquid Display Entities
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/invalid_recipe.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/lingering/check_liquid.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/potions/splash/check_liquid.mcfunction
Labels: fix

#944 Move CSV utils to gm4.utils
  gm4/utils.py
  gm4_zauber_cauldrons/generate.py
Labels: tested, tool

#942 Zauber Liquids & Mob Curing: Enable Compatibility with Zauber Cauldrons v1.10
  gm4_mob_curing/beet.yaml
  gm4_mob_curing/data/gm4_mob_curing/loot_tables/technical/potion_cleric/zauber/drinkable.json
  gm4_mob_curing/data/gm4_mob_curing/loot_tables/technical/potion_cleric/zauber/lingering.json
  gm4_mob_curing/data/gm4_mob_curing/loot_tables/technical/potion_cleric/zauber/splash.json
  gm4_zauber_liquids/beet.yaml
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_harming_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_healing_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_leaping_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_poison_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_regeneration_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_strength_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_swiftness_potion.mcfunction
  gm4_zauber_liquids/data/gm4_zauber_liquids/functions/item_fill/zauber_wormhole_potion.mcfunction
Labels: fix

#943 Bookshelf Inspector Bugfix
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/process_display/remove/process.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/process_display/remove/tick.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/process_display/spawn/process.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/process_display/spawn/tick.mcfunction
Labels: tested, fix

#945 Your Sparks is in another castle!
  contributors.json
Labels: fix
