Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2024-02, with the labels that each got.

#952 Bookshelf Inspector: Optimise & Simplify Everything
  gm4_bookshelf_inspector/beet.yaml
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/evaluate/calc_distance.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/evaluate/get_pos.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/evaluate/position.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/evaluate/raycast.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/evaluate/rotation.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/evaluate/run.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/find_book/find_book.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/find_book/get_book_slot.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/find_book/get_rotation.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/find_book/prep.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/init.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/main.mcfunction
  gm4_bookshelf_inspector/data/gm4_bookshelf_inspector/functions/process_display/remove/process.mcfunction
Labels: quality-update

#953 Add Trident to Hypexperia
  gm4_metallurgy/data/gm4_hypexperia_shamir/functions/mark_item_validity.mcfunction
Labels: feature-update

#951 Hotfix: Make destroying custom carts drop the correct item
  gm4_liquid_minecarts/overlay_26/data/gm4_liquid_minecarts/functions/machine/destroy_cart.mcfunction
  gm4_liquid_minecarts/overlay_26/data/gm4_liquid_minecarts/functions/machine/destroy_cart/scan_hoppers.mcfunction
  gm4_liquid_minecarts/overlay_26/data/gm4_liquid_minecarts/functions/machine/destroy_cart/update_hopper.mcfunction
  gm4_liquid_minecarts/overlay_26/data/gm4_liquid_minecarts/functions/machine/destroy_cart/update_hopper_minecart.mcfunction
  gm4_tunnel_bores/overlay_26/data/gm4_tunnel_bores/functions/machine/destroy_cart.mcfunction
  gm4_tunnel_bores/overlay_26/data/gm4_tunnel_bores/functions/machine/destroy_cart/scan_hoppers.mcfunction
  gm4_tunnel_bores/overlay_26/data/gm4_tunnel_bores/functions/machine/destroy_cart/update_hopper.mcfunction
  gm4_tunnel_bores/overlay_26/data/gm4_tunnel_bores/functions/machine/destroy_cart/update_hopper_minecart.mcfunction
Labels: server-testing

#958 Infinitas Shamir: Waterlogging blocks no longer breaks the shamir
  base/data/gm4/tags/blocks/waterloggable.json
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/place_mainhand.json
  gm4_metallurgy/data/gm4_infinitas_shamir/advancements/water/place_offhand.json
  gm4_metallurgy/data/gm4_metallurgy/predicates/infinitas_active.json
Labels: fix, server-testing

#961 Update to mecha 0.87.0 and pydantic v2
  gm4/plugins/manifest.py
  gm4/plugins/player_heads.py
  gm4/plugins/prefabs.py
  gm4/plugins/upgrade_paths.py
  gm4/plugins/versioning.py
  gm4_guidebook/generate_guidebooks.py
  poetry.lock
  pyproject.toml
Labels: tool

#948 Mysterious midnights seed based randomization
  gm4_mysterious_midnights/overlay_18/data/gm4_mysterious_midnights/functions/calculate_difficulty.mcfunction
  gm4_mysterious_midnights/overlay_18/data/gm4_mysterious_midnights/functions/roll_difficulty.mcfunction
Labels: feature-update, server-testing

#959 Soul Glass: Hotfix Module Not Applying Effects
  gm4_soul_glass/overlay_18/data/gm4_soul_glass/functions/effect/check.mcfunction
  gm4_soul_glass/overlay_18/data/gm4_soul_glass/functions/effect/obtain_numeric_primary_id.mcfunction
  gm4_soul_glass/overlay_18/data/gm4_soul_glass/functions/effect/obtain_numeric_secondary_id.mcfunction
  gm4_soul_glass/overlay_18/data/gm4_soul_glass/functions/effect/update_effects.mcfunction
Labels: fix, server-testing

#956 Zauber Cauldrons: Only Allow Magicol Bottling at Night
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/extra_items/release_from_bottle/check_timer.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/extra_items/release_from_bottle/crack_bottle.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/liquid/magicol/check_moon_phase.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/cauldron/liquid/magicol/particles.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/player/crystal/swap/restore_player_head.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/functions/recipes/magicol/bottled/wrong_moon_phase.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/predicates/cauldron/clear_night.json
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/templates/functions/magicol/craft_bottled_magicol.mcfunction
  gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/templates/loot_tables/zauber_crystal.json
Labels: feature-update, server-testing

#967 Better Fire: Fix Flint drop
  gm4_better_fire/data/gm4_better_fire/functions/arrow.mcfunction
Labels: fix

#962 Infinitas Shamir: Unsmooshing fix
  gm4_metallurgy/data/gm4_metallurgy/functions/init.mcfunction
Labels: fix, server-testing

#964 Spawner Minecarts: Use Zauber Cauldron's Flower Algorithm
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/fuel/initiate_flower_types.mcfunction
  gm4_spawner_minecarts/data/gm4_spawner_minecarts/functions/init.mcfunction
Labels: fix, server-testing

#968 Metallurgy: Blazing-Hot-Fix Execution Location on Molds
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/destroy_mould.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/overheat_mould.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/set_mould.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/casting/sustain_mould.mcfunction
  gm4_metallurgy/data/gm4_metallurgy/functions/main.mcfunction
  gm4_metallurgy/overlay_26/data/gm4_metallurgy/functions/main.mcfunction
Labels: fix, server-testing
