Repository Gamemode4Dev/GM4_Datapacks, pull requests merged in 2025-02, with the labels that each got.

#1070 Blossoming Pots
  gm4/contributors.json
  gm4_blossoming_pots/README.md
  gm4_blossoming_pots/beet.yaml
  gm4_blossoming_pots/data/gm4_blossoming_pots/advancement/interact_with_decorated_pot.json
  gm4_blossoming_pots/data/gm4_blossoming_pots/advancement/interact_with_flower_pot.json
  gm4_blossoming_pots/data/gm4_blossoming_pots/advancement/interact_with_vanilla_flower_pot.json
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/as_player.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/check_if_pot_empty.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/get_player_rotation.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/in_decorated_pot.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/play_sound.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/prepare_data.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/raycast.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/set_count.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/set_displays.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/set_storage.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/decorated/set_temp_data.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/as_player.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/cleanup.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/get_player_data.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/give_item_to_player.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/in_flower_pot.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/play_sound.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/prepare_data.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/raycast.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/remove_plant.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/set_displays.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/set_full.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/set_storage.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/set_temp_data.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/store_array_len.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/flower/update_count.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/init.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/main.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/vanilla_pot_handling/as_marker.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/vanilla_pot_handling/as_player.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/vanilla_pot_handling/get_dropped_item.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/vanilla_pot_handling/give_item_back.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/vanilla_pot_handling/in_vanilla_flower_pot.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/function/vanilla_pot_handling/raycast.mcfunction
  gm4_blossoming_pots/data/gm4_blossoming_pots/item_modifier/count_decr.json
  gm4_blossoming_pots/data/gm4_blossoming_pots/predicate/item_potable.json
  gm4_blossoming_pots/data/gm4_blossoming_pots/tags/block/potted_plants.json
  gm4_blossoming_pots/data/gm4_blossoming_pots/tags/item/potable_plants.json
  gm4_blossoming_pots/images/blossoming_pots.webp
  gm4_blossoming_pots/pack.png
  gm4_blossoming_pots/pack.svg
  gm4_blossoming_pots/since_61/data/gm4_blossoming_pots/function/decorated/set_storage.mcfunction
  gm4_blossoming_pots/since_61/data/gm4_blossoming_pots/function/flower/set_storage.mcfunction
  gm4_blossoming_pots/since_61/data/gm4_blossoming_pots/function/init.mcfunction
  gm4_blossoming_pots/since_61/data/gm4_blossoming_pots/tags/block/potted_plants.json
  gm4_blossoming_pots/since_61/data/gm4_blossoming_pots/tags/item/potable_plants.json
Labels: submission, needs-testing

#1101 Fix Standard Crafting Missing Slab & Stair Uncrafting Recipes
  gm4_standard_crafting/generate_recipes.py
Labels: fix

#1081 Crossbow Cartridges 1.21: Torch place fix
  gm4_crossbow_cartridges/data/gm4_crossbow_cartridges/function/projectile/torch/place.mcfunction
Labels: tested, fix
